### ISSUE TITLE
TypeError: [BABEL]  Cannot read properties of undefined (reading 'uid') while running test suite.

### ISSUE THREAD

**Issue by AadarshGhodasara** [testing-library/react-testing-library#1136] opened 2022-10-07 05:17 UTC
- `@testing-library/react` version: 13.4.0
- Testing Framework and version: ReactJS ( 16.9.0 )
  
- DOM Environment: react-dom (16.9.0)
  

### Relevant code or config:
.eslintrc.json
```.json
{
  "plugins": ["testing-library", "jest-dom"],
  "extends": [
    "react-app",
    "react-app/jest",
    "plugin:testing-library/react",
    "plugin:jest-dom/recommended"
  ]
}
```

config-overrides.js : In this config file, we set up only weback and babel plugins.
```.js
const CompressionPlugin = require('compression-webpack-plugin')
const webpack = require('webpack')
const path = require('path')
const {
  addWebpackAlias,
  override,
  fixBabelImports,
  addLessLoader,
  useBabelRc,
  addExternalBabelPlugins,
  addWebpackPlugin,
} = require('customize-cra')

module.exports = override(
  ...addExternalBabelPlugins('@babel/plugin-proposal-optional-chaining'),
  useBabelRc(),
  fixBabelImports('import', {
    libraryName: 'antd',
    libraryDirectory: 'es',
    style: true,
  }),
  addWebpackAlias({
    ['Assests']: path.resolve(__dirname, 'src/Assets'),
  }),
  addLessLoader({
    javascriptEnabled: true,
    modifyVars: {
      //Theme
      '@primary-color': '#077579',
      '@body-background': '#ffffff',
      '@font-family': 'circularStd',
      '@code-family': 'circularStd',
      '@text-color': '#111111',
      '@heading-color': '#111111',
      '@font-size-base': '14px',
      // Button
      '@btn-border-radius-base': '0px',
      '@btn-border-radius-sm': '@border-radius-base',
      '@btn-height-base': '36px',
      '@btn-height-lg': '44px',
      '@btn-height-sm': '30px',
      // Input
      '@input-height-base': '36px',
      '@input-height-lg': '44px',
      '@input-height-sm': '30px',
      // Tabs
      '@tabs-card-head-background': '@body-background',
      '@tabs-card-height': '36px',
      '@tabs-card-active-color': '@primary-color',
      '@tabs-title-font-size': '14px',
      '@tabs-hover-color': '@primary-color',
      '@tabs-active-color': '@primary-color',
      '@tabs-card-gutter': '0px',
      // Forms
      '@label-required-color': '#ff0000',
      '@label-color': '#111111',
      '@form-item-label-font-size': '13px',
      '@form-item-label-height': 'auto',
      '@form-item-margin-bottom': '20px',
      // Menu (Header navigation)
      '@menu-item-height': '20px',
      '@menu-collapsed-width': '90%',
      '@menu-bg': '#077579',
      '@menu-item-color': '#ffffff',
      '@menu-item-font-size': '16px',
      // Avatar
      '@avatar-size-base': '36px',
      // Badge
      '@badge-dot-size': '7px',
      // height rules
      '@height-base': '36px',
      '@height-lg': '44px',
      '@height-sm': '30px',
      // Table
      '@table-header-bg': '#fbfbfb',
      '@table-header-color': '#808498',
      '@table-expand-icon-bg': 'transparent',
      // Description
      '@descriptions-item-padding-bottom': '5px',
      '@rate-star-bg': '#a8aab7',
    },
  }),
  addWebpackPlugin(new webpack.DefinePlugin(new CompressionPlugin()))
)

```

Home.test.js
```.test.js
test('sample test cases', () => {})
```

Version List --->

Node Version: 16.13.2
NPM Version: 8.1.2
Yarn Version: 1.22.17
"@testing-library/jest-dom": "^5.16.5",
"@testing-library/react": "^13.4.0",
"@testing-library/user-event": "^14.4.3",

### What you did:
Our React Project is working on the 16.9.0 version. We need to implement react testing library so for that we set up react testing library and configure some eslint rules for the testing library. After that, we create the first test file And write code as above mention Home.test.js file. After that when we run the file we got the Error. 

### Problem description:

- When we run the test suite using the yarn test command then we got a type error.
- We also do not use the externally graceful-fs npm package. Still, got errors from that package while running the test suit.
- As you can see the error is in the below image.

![download (1)](https://user-images.githubusercontent.com/47548524/194794423-1835f1c2-8b18-4de9-b20e-70ae1e3cba85.png)

Help me to fix this.
Thank You In Advance 🙂️.

**Comment by MatanBobi** [comment] 2022-10-07 05:29
Hi @AadarshGhodasara!
First thing, for React versions lower than 18, you'll need RTL version lower than 13 (which is only compatible with React 18).
Please try to install RTL 12 and update here if the issue still persists.

**Comment by AadarshGhodasara** [comment] 2022-10-07 05:38
Hi @MatanBobi 
I installed RTL 12 but still got the same error. 
"@testing-library/react": "12.0.0",

**Comment by MatanBobi** [comment] 2022-10-09 06:18
If that's the case, it's probably something with your setup.
Can you please provide a minimal reproduction for us to investigate and try to help?
You can find guidelines on how to create a minimal reproducible example in [stackoverflow](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by eps1lon** [comment] 2023-02-16 17:15
Closing since no repro was provided

**Closed by eps1lon** 2023-02-16 17:16 UTC

**Comment by marcosvcloures** [comment] 2024-04-18 14:06
If it helps, what causes this problem is a bugged version of the `graceful-fs`, upgrading it to 4.2.9 solves this problem.

#https://github.com/meteor/meteor/issues/11940#issuecomment-1046806837
