### ISSUE TITLE
Wrapper for render that returns SVGElements improperly type-checks

### ISSUE THREAD

**Issue by joebobmiles** [testing-library/react-testing-library#934] opened 2021-06-15 02:59 UTC
- `@testing-library/react` version: 11.2.7
- Testing Framework and version: jest 25.5.4
- DOM Environment: jsdom 15.2.1

### Relevant code or config:

```ts
import * as React from "react";
import { render, RenderOptions, RenderResult } from "@testing-library/react";

type Queries = typeof import("@testing-library/dom/types/queries");

export const renderSVG = (
  ui: React.ReactElement,
  options?: RenderOptions<Queries, SVGElement>
): RenderResult<Queries, SVGElement> =>
  render<Queries, SVGElement>(
    ui,
    {
      container:
        document.body.appendChild(
          document.createElementNS("http://www.w3.org/2000/svg", "svg")
        ),
      ...options,
    }
  );
```

### What you did:

I'm building an app that has mixed HTML and SVG, with SVG forming a bulk of the interactive components. SVG elements can't be created and added as children to HTML elements without crashing the test runner. My solution has been to make the container an SVG element created with the SVG namespace. This was working in earlier versions (with a patch I pushed earlier so that render() accepted both HTMLElement and SVGElement types.)

However, after upgrading my dependencies, this no longer type checks in TypeScript. I see the types have been refactored significantly since the last time I worked with them.

### What happened:

Originally, the code was this:

```ts
import * as React from "react";
import { render } from "@testing-library/react";

export const renderSVG = (
  ui: React.ReactElement,
  options?: RenderOptions
): RenderResult =>
  render(
    ui,
    {
      container:
        document.body.appendChild(
          document.createElementNS("http://www.w3.org/2000/svg", "svg")
        ),
      ...options,
    }
  );
```

But TypeScript reported a verbose type error that reported that I was trying to assign a RenderResult whose Container was of type `HTMLElement | SVGElement` to a RenderResult whose Container was `HTMLElement`. After changing the code to:

```ts
import * as React from "react";
import { render, RenderOptions, RenderResult } from "@testing-library/react";

type Queries = typeof import("@testing-library/dom/types/queries");

export const renderSVG = (
  ui: React.ReactElement,
  options?: RenderOptions<Queries, SVGElement>
): RenderResult<Queries, SVGElement> =>
  render<Queries, SVGElement>(
    ui,
    {
      container:
        document.body.appendChild(
          document.createElementNS("http://www.w3.org/2000/svg", "svg")
        ),
      ...options,
    }
  );
```

VS Code running the TypeScript compiler reports that the code type checks. However, when I run my test with Jest, the tests fail with the same type error that was reported before I specified the type parameters.

The full error text:

```
    src/components/vtt/Token.spec.tsx:11:3 - error TS2322: Type 'RenderResult<typeof import("C:/Users/josep/Documents/Programming/TypeScript/TableTop/node_modules/@testing-library/dom/types/queries"), HTMLElement | SVGSVGElement>' is not assignable to type 'RenderResult<typeof import("C:/Users/josep/Documents/Programming/TypeScript/TableTop/node_modules/@testing-library/dom/types/queries"), HTMLElement>'.
      Type 'RenderResult<typeof import("C:/Users/josep/Documents/Programming/TypeScript/TableTop/node_modules/@testing-library/dom/types/queries"), HTMLElement | SVGSVGElement>' is not assignable to type '{ container: HTMLElement; baseElement: Element; debug: (baseElement?: Element | DocumentFragment | (Element | DocumentFragment)[], maxLength?: number, options?: OptionsReceived) => void; rerender: (ui: ReactElement<...>) => void; 
unmount: () => void; asFragment: () => DocumentFragment; }'.
        Types of property 'container' are incompatible.
          Type 'HTMLElement | SVGSVGElement' is not assignable to type 'HTMLElement'.
            Type 'SVGSVGElement' is missing the following properties from type 'HTMLElement': accessKey, accessKeyLabel, autocapitalize, dir, and 16 more.

     11   render(
          ~~~~~~~
     12     ui,
        ~~~~~~~
    ...
     17       ...options,
        ~~~~~~~~~~~~~~~~~
     18     });
        ~~~~~~
```

### Reproduction:

I have been unable to replicate this problem in a new project. In fact, in the project I created to replicate this bug, I found everything to work exactly as expected.

### Problem description:

Being able to test apps that use SVG makes sense since React doesn't prevent developers from writing components that use SVG tags. The React Testing Library not properly type checking breaks the workflow for developers who have been using SVG tags in their React projects.

### Suggested solution:

I'm not sure what the solution is here. I thought all I had to do was supply the type parameters, but that only seems to satisfy TypeScript type checks for linting.

**Comment by eps1lon** [comment] 2021-06-15 04:37
Thanks for the feedback.

> I have been unable to replicate this problem in a new project. In fact, in the project I created to replicate this bug, I found everything to work exactly as expected.

It sounds like this is not an issue with testing-library but your project setup. Once you are able to replicate the bug, feel free to open a new issue including the reproducible issue.

Until then I have to close this issue since there's nothing actionable here for us.

**Closed by eps1lon** 2021-06-15 04:37 UTC
