### ISSUE TITLE
useEffect not triggering inside jest

### ISSUE THREAD

**Issue by peterjuras** [testing-library/react-testing-library#215] opened 2018-11-03 12:26 UTC
- `react-testing-library` version: 5.2.3
- `react` version: 16.7.0-alpha.0
- `node` version: CodeSandbox
- `npm` (or `yarn`) version: CodeSandbox

### Relevant code or config:

```js
  let a = false;
  function Test() {
    React.useEffect(() => {
      a = true;
    });
    return <div>Hello World</div>;
  }
  render(<Test />);
  expect(a).toBe(true);
```

### What you did:

I'm trying to test functions with the `useEffect` hook inside jest.

### What happened:

The useEffect hook is not executed correctly inside a jest environment after calling `render(<Test />)`. However it appears to be working correctly if it is called directly in a browser environment.

### Reproduction:

Working example: https://codesandbox.io/s/l947z8v6xq (index.js)
Not working example in jest: https://codesandbox.io/s/7k5oj92740 (index.test.js)

### Problem description:

The `useEffect` hook should have been executed after the `render` call

**Comment by sivkoff** [comment] 2018-11-03 14:33
That's because React doesn't run the hook in sync mode. If you rerender the component the second time it changes `a` to `true`: https://codesandbox.io/s/m5m5yqrr18

**Comment by wzrdzl** [comment] 2018-11-03 18:59
@sivkoff any idea why this happens and whether this will be fixed either in react or in react-testing-library?

**Comment by sivkoff** [comment] 2018-11-04 05:12
@wzrdzl, I'm not sure if it will not be fixed, because it is a documented behavior:
> Unlike `componentDidMount` and `componentDidUpdate`, the function passed to `useEffect` fires after layout and paint, during a deferred event. This makes it suitable for the many common side effects, like setting up subscriptions and event handlers, because most types of work shouldn’t block the browser from updating the screen.

More details in [React Hooks](https://reactjs.org/docs/hooks-reference.html) reference: https://reactjs.org/docs/hooks-reference.html#timing-of-effects

**Comment by alexkrolick** [comment] 2018-11-04 05:54
You might want to use the waitForElement or wait utils to asynchronously await the _result_ of the hook, or try these auto-retrying queries if your environment is highly asynchronous https://github.com/alexkrolick/dom-testing-addon-async

**Comment by wzrdzl** [comment] 2018-11-04 09:18
@sivkoff thanks for pointing to the docs, so as I understand the root cause of this problem is not really the "sync" test code. My test code looks like this and it also breaks without a re-render:
```js
it('should render a spinner after `showAfterDelay` milliseconds', () => {
      jest.useFakeTimers();
      // LoadingIndicator uses useEffect internal to schedule the rendering after a delay (setTimeout)
      const { getByTestId, rerender } = render(<LoadingIndicator showAfterDelay={500} />);

      // no spinner initially
      expect(() => getByTestId(LOADING_SPINNER_CONTAINER_TEST_ID)).toThrow();

      // now you need to rerender for React to run the `useEffect` hook
      // this should hopefully be fixed or worked around with some new react-testing-library API
      // this is the price you pay for riding the hype train :)
      // https://github.com/kentcdodds/react-testing-library/issues/215#issuecomment-435592444
      rerender(<LoadingIndicator showAfterDelay={500} />);

      jest.advanceTimersByTime(500);

      expect(getByTestId(LOADING_SPINNER_CONTAINER_TEST_ID)).toBeTruthy();
    });
```

Looks like the issue is that the React's "determine paint event" logic doesn't work in `jsdom` (my wild guess) so I wonder if we can somehow fix that, because using `rerender` looks like a workaround but not really a solution

**Comment by alexkrolick** [comment] 2018-11-04 09:47
Could it be that `showAfterDelay` only _schedules_ after 500ms, so you need to wait a bit longer than that before running synchronous `expect`s? Try waiting with the mutation observer helper `waitForDomChange` or one of the other helpers.

```js
import {waitForDomChange} from 'dom-testing-library'

it('should render a spinner after `showAfterDelay` milliseconds', () => {
      // LoadingIndicator uses useEffect internal to schedule the rendering after a delay (setTimeout)
      const { getByTestId, rerender } = render(<LoadingIndicator showAfterDelay={500} />);

      // no spinner initially
      expect(() => getByTestId(LOADING_SPINNER_CONTAINER_TEST_ID)).toThrow();

      // now you need to rerender for React to run the `useEffect` hook
      // this should hopefully be fixed or worked around with some new react-testing-library API
      // this is the price you pay for riding the hype train :)
      // https://github.com/kentcdodds/react-testing-library/issues/215#issuecomment-435592444
      
      await waitForDomChange()

      expect(getByTestId(LOADING_SPINNER_CONTAINER_TEST_ID)).toBeTruthy();
    });
```

**Comment by sivkoff** [comment] 2018-11-04 10:41
@wzrdzl There is another simple workaround for your case — you just need to rerender it once again 😄

Let me explain how it works (probably I'm wrong):
- the first render initializes the hook
- the second render resolves the callback and runs the timer
- before the third render you need to advance your timer, so when you render it again, your component will already have changed state.

I agree this workaround is ugly, but not sure if it makes sense to fix the case before React core team releases the stable version. Furthermore example with lifecycle alternative works well, so I think `jsdom` handles React event logic.

I've created a repo with the example so you can clone and make sure:
https://github.com/sivkoff/hooks-testing-sandbox
Unfortunatelly CodeSandbox doesn't support mocking timers, so you need to clone it to localhost.

**Comment by kentcdodds** [comment] 2018-11-04 15:02
You may also be interesting in http://kcd.im/hooks-and-suspense

I have a video in there that explains one of the big nuances with testing effect hooks.

I do plan on creating a small function called `flushEffects` or something that'll make this easier.

**Comment by alexkrolick** [comment] 2018-11-04 18:20
@kentcdodds special case handling for side-effectful components seems like it's letting implementation details shape the tests. What about adding `{ flushEffects: [true] }` to the render options?

**Comment by kentcdodds** [comment] 2018-11-04 18:58
If prefer that to just be the default. If we can make that work then let's do it. I just don't think it's possible

**Comment by kentcdodds** [comment] 2018-11-06 22:12
@FredyC, don't feel dumb 🤗 

It's really odd, but I observed that `wait` works if you run your tests in the browser but does not work if you run them in jsdom (which most people testing react will be doing). I never dug into the reason (my guess is it's an issue with react's scheduler and jsdom/jest timers) because I don't want to have to use `wait`. I want to find another solution.

**Comment by zaguiini** [comment] 2018-11-13 14:53
I think the key part is when @kentcdodds explains that you need to rerender to get `useEffect` results. Really took me all morning to fix that 👎 

Anyways, thanks a lot!

(I don't think React will change the way that `useEffect` behaves because that's what it is intended to: don't block the rendering process.)

**Comment by kentcdodds** [comment] 2018-11-13 14:54
Currently the way that I dislike the least for making this work nicely is to put this in my setup file:

```javascript
beforeAll(() => jest.spyOn(React, 'useEffect').mockImplementation(React.useLayoutEffect))
afterAll(() => React.useEffect.mockRestore())
```

I don't like it, but it's my favorite anyway...

**Comment by zaguiini** [comment] 2018-11-13 14:58
> Currently the way that I dislike the least for making this work nicely is to put this in my setup file:
> 
> ```js
> beforeAll(() => jest.spyOn(React, 'useEffect').mockImplementation(React.useLayoutEffect))
> afterAll(() => React.useEffect.mockRestore())
> ```
> 
> I don't like it, but it's my favorite anyway...

But are they exactly the same apart from don't block the rendering process?

**Comment by FredyC** [comment] 2018-11-13 15:33
@kentcdodds Have you considering this approach? Feels much easier imo ... https://github.com/facebook/react/issues/14050#issuecomment-438173736

**Comment by kentcdodds** [comment] 2018-11-13 16:15
Basically the same except there's no way to clean up. So if you wanted to get the original `useEffect` back for a certain test for some reason you wouldn't be able to. I suppose you could use that mock to do the spy stuff though 🤷‍♂️ I cool with either. But I'm still not super happy with it. Hoping the react team comes up with something else...

**Comment by ivan-kleshnin** [comment] 2018-11-23 18:15
For some reasone this workaround:

```
beforeAll(() => jest.spyOn(React, 'useEffect').mockImplementation(React.useLayoutEffect))
afterAll(() => React.useEffect.mockRestore())
```

has no effect on my Jest tests, effects just never happen. Only manual replacement of `useEffect` with `useLayoutEffect` in components helps. I know it's not a QA thread but this is relevant to the issue.

**Comment by zaguiini** [comment] 2018-11-23 18:43
> I'm actually starting to think that it's better to manually trigger effects. That's why I added the experiential `flushEffects` function (see the docs).

Noooooooo. That would be an implementation detail. The user don't actually flush the effects. In fact, they don't even know what an effect isssss :/

**Comment by pelotom** [comment] 2018-11-23 18:43
@kentcdodds idk, it feels a little like the test having too much awareness of implementation details

**Comment by kentcdodds** [comment] 2018-11-23 18:59
I agree, but at the same time, one could argue that running anything synchronously is an implementation detail. If we really wanted to be free of implementation details then everything we do with react-testing-library would be asynchronous.

The thing is that if you force `useEffect` to run synchronously, you're actually not simulating what the user's experiencing. What about the state between when the render runs and effect callback runs? How would you test that state?

**Comment by pelotom** [comment] 2018-11-23 20:01
>The thing is that if you force useEffect to run synchronously, you're actually not simulating what the user's experiencing. What about the state between when the render runs and effect callback runs? How would you test that state?

Is that an actual observable frame? I didn’t realize that, but then I’m not too familiar with concurrent react yet. Still, I’m having trouble imagining a case where I’d care to test that intermediate state.

**Comment by alexkrolick** [comment] 2018-11-23 20:36
1. As close as possible to production mode: `useEffect` runs async in JSDOM the same way it does in-browser, and  `flushEffects` is only used to skip to the end state for slow effects or debugging. Without `flushEffects` the end state should be awaited using `waitForElement` or an async query. As we know, this doesn't work right now for some reason, so you need `flushEffects` to get `useEffect` (unless you mock it to point at `useLayoutEffect`).
2. Force sync mode for the entire React tree changing what's passed to `ReactDOM.render`. I _think_ the intermediate state would still be committed to the DOM, but `useEffect` effects would process immediately afterward and do whatever they do.

**Closed as completed** 2018-11-24 05:26 UTC
Labels: enhancement

**Comment by alflennik** [comment] 2019-02-25 16:22
The lack of coverage for my useEffect code led me here. It's been three months since the issue was closed, but I'm feeling the pain right now. I would absolutely love an automatic flushEffects feature. Without it, how am I supposed to test my side effects? I am not going to introduce timeouts into my tests.

**Comment by FredyC** [comment] 2019-02-25 17:14
@alflennik https://github.com/threepointone/react-act-examples and please use latest RTL

**Comment by matewilk** [comment] 2019-04-23 13:18
It seems the topic diverged a little bit but going back to the original issue. 
Why not just use `jest.spyOn(React, 'useEffect`)` and test it this way?

**Comment by FredyC** [comment] 2019-04-23 13:54
@matewilk Because you are testing implementation detail then? Seriously, just grab the awesome `act` (especially the one from 16.9 alpha) and you are golden.

**Comment by afenton90** [comment] 2019-07-09 12:36
@FredyC I followed the documentation you have linked to, but no wrapping of `render` or `event` in the `act` function allows for the effects to asynchronously update the component after its initial render.

Would be great to work together on this issue to get something more obvious working for tests which need to assert side effects on the DOM. At the moment anything in `useEffect` is untestable if it has an effect on the DOM.

**Comment by romulof** [comment] 2025-03-12 17:34
In my use-case I could not directly detect in DOM the results of `useLayoutEffect`, so I did this:

- Component:
```js
useLayoutEffect(() => {
  whatever()
  if (process.env.NODE_ENV === 'test') {
    console.warn('useLayoutEffect');
  }
}, [whatever]);
```
- Test
```js
beforeAll(() => {
  const originalConsoleWarn = console.warn;
  jest.spyOn(console, 'warn').mockImplementation((message, ...args) => {
    if (message !== 'useLayoutEffect') {
      // Do not accidentally suppress other warnings
      originalConsoleWarn(message, ...args);
    }
  });
});

const renderComponent = () => {
  const result = render(<Whatever/>);
  await waitFor(() => {
    expect(console.warn).toHaveBeenCalledWith('updateCollapse');
  });
  return result;
}
```

This way I can safely await until `useLayoutEffect` is called.
