### ISSUE TITLE
The checkbox triggers the change event, and the checked value cannot be obtained

### ISSUE THREAD

**Issue by yunithl** [testing-library/react-testing-library#889] opened 2021-03-25 11:52 UTC

**Comment by MatanBobi** [comment] 2021-03-25 16:22
Hi @yunithl, can you please add some details about this one? A reproduction, the version you're using, the test code and the components so we'll be able to help?

**Comment by eps1lon** [comment] 2021-06-02 10:19
Closing since no reproduction was provided.

**Closed by eps1lon** 2021-06-02 10:19 UTC
Labels: question
