### ISSUE TITLE
Mock XML file fetch in test?

### ISSUE THREAD

**Issue by stavrosgemis** [testing-library/react-testing-library#939] opened 2021-07-07 16:31 UTC
- `@testing-library/react` version: ^11.2.7
- Testing Framework and version: React ^17.0.2
  
- DOM Environment: @testing-library/jest-dom: "^5.14.1"
  

### Relevant code or config:

Component
```js
function MunicipalityInfo() {
  const [municipalityData, setMunicipalityData] = useState({})

  const fetchData = async () => {
    try{
      const result = await fetch(XMLFile)
      const data = await result.text();
      const xml = new XMLParser().parseFromString(data);
      const res = XMLMapper(xml) <--- builds a json object of the XML
      setMunicipalityData(res)
    }catch(e){
      console.log(e)
    }
  }

  useEffect(() => {
    fetchData();
  }, []); 

  return(
    <>
      { municipalityData.units &&
        municipalityData.units.map((city, index) => {
          return (
            <Div key={index} data-testid="municipalityInfo-component" className="mt-5 p-3">
              <LinkList data-testid="link-list">
                <LinkListItem data-testid="list-item">
                  <Link href={city.BookingURL} data-testid="link-book-vaccination">Some nice link</Link>
                </LinkListItem>
              </LinkList>
            </Div>
          )
        })
      }
    </>
  )
}

export default MunicipalityInfo;
```
The Test:

```js
import { render, screen } from '@testing-library/react';
import MunicipalityInfo from './MunicipalityInfo';


  test("renders without crashing", async () => {
    render(<MunicipalityInfo />);

    expect(await screen.findByText("Some nice link")).toBeInTheDocument();
  })
```
The Error:

```js
Unable to find an element with the text: Some nice link. This could be because the text is broken up by multiple elements. In this case, you can provide a function for your text matcher to make your matcher more flexible.

    <body>
      <div />
    </body>

       7 |     render(<MunicipalityInfo />);
       8 |
    >  9 |     expect(await screen.findByText("Some nice link")).toBeInTheDocument();
         |                         ^
      10 |   })
      11 |
      12 |

      at waitForWrapper (node_modules/@testing-library/dom/dist/wait-for.js:173:27)
      at findByText (node_modules/@testing-library/dom/dist/query-helpers.js:101:33)
      at Object.<anonymous> (src/Components/MunicipalityInfo/MunicipalityInfo.test.js:9:25)

Test Suites: 1 failed, 3 passed, 4 total
Tests:       1 failed, 6 passed, 7 total
Snapshots:   0 total
Time:        2.951 s, estimated 3 s
Ran all test suites related to changed files.
```

### What you did:
I have an XML file that i pass in my fetch, from there i am trying to test that the component renders correctly after the useEffect hook has fetched the data.
The app is running just fine but the test fails.

### What happened:
See the Error that i provided in the code further up. ☝️ 

### Problem description:
Im using async and await in my fetch and also marked my test as async, i goooled a lot and found many examples but nothing can get the test to pass.

My fetch is working and its fetches the data.

### Suggested solution:
I dont have one right now 😞

**Comment by dariolingotti** [comment] 2021-07-08 21:19
I solved this not importing render from '@testing-library/react'. That breaks the content. You should import it from "react-dom".
I hope they mark as obsolete that nasty "render" method in a future version.

**Comment by stavrosgemis** [comment] 2021-07-09 20:34
Actually the problem seems to be the XML file, when i use a rest API the test passes when i mock the http request with MSW.
When using a rest api i can se that the DOM is being poupulated with data but not when i use the XML file.

Test:
`import { render, screen } from '@testing-library/react';
import MunicipalityInfo from './MunicipalityInfo';
import {setupServer} from 'msw/node';
import {rest} from 'msw';

  const data = {
    cities: [
        "Västervik",
        "Kalmar",
        "Emmaboda",
        "",
        "Nybro",
        "Hultsfred",
        "Oskarshamn",
        "Vimmerby",
        "Borgholm",
        "Högsby",
        "Virserum",
        "Mönsterås",
        "Mörbylånga",
        "Ankarsrum",
        "Blomstermåla",
        "Färjestaden",
        "Gamleby",
        "Löttorp",
        "Mörlunda",
        "Torsås"
    ],
    units: [
          {
            unit: [
                {
                    date: "2021-07-01",
                    time_slots: "0"
                },
                {
                    date: "2021-07-02",
                    time_slots: "0"
                },
                {
                    date: "2021-07-03",
                    time_slots: "0"
                },
                {
                    date: "2021-07-04",
                    time_slots: "0"
                },
                {
                    date: "2021-07-05",
                    time_slots: "0"
                },
                {
                    date: "2021-07-06",
                    time_slots: "0"
                },
                {
                    date: "2021-07-07",
                    time_slots: "0"
                },
                {
                    date: "2021-07-08",
                    time_slots: "0"
                },
                {
                    date: "2021-07-09",
                    time_slots: "0"
                },
                {
                    date: "2021-07-10",
                    time_slots: "0"
                },
                {
                    date: "2021-07-11",
                    time_slots: "0"
                },
                {
                    date: "2021-07-12",
                    time_slots: "0"
                },
                {
                    date: "2021-07-13",
                    time_slots: "0"
                },
                {
                    date: "2021-07-14",
                    time_slots: "0"
                }
            ],
            veid: "503",
            venamn: "Mörbylånga hälsocentrals vaccinationsmottagning",
            Address: "Rönningevägen 2",
            City: "Mörbylånga",
            PostCode: "38602",
            BookingURL: "https://bokning.mittvaccin.se/klinik/503/bokning"
        },
        {
            "unit": [
                {
                    date: "2021-07-01",
                    time_slots: "0"
                },
                {
                    date: "2021-07-02",
                    time_slots: "0"
                },
                {
                    date: "2021-07-03",
                    time_slots: "0"
                },
                {
                    date: "2021-07-04",
                    time_slots: "0"
                },
                {
                    date: "2021-07-05",
                    time_slots: "0"
                },
                {
                    date: "2021-07-06",
                    time_slots: "0"
                },
                {
                    date: "2021-07-07",
                    time_slots: "7"
                },
                {
                    date: "2021-07-08",
                    time_slots: "55"
                },
                {
                    date: "2021-07-09",
                    time_slots: "0"
                },
                {
                    date: "2021-07-10",
                    time_slots: "0"
                },
                {
                    date: "2021-07-11",
                    time_slots: "0"
                },
                {
                    date: "2021-07-12",
                    time_slots: "0"
                },
                {
                    date: "2021-07-13",
                    time_slots: "0"
                },
                {
                    date: "2021-07-14",
                    time_slots: "0"
                }
            ],
            veid: "515",
            venamn: "Mörlunda hälsocentral",
            Address: "Doktorsvägen 6",
            City: "Mörlunda",
            PostCode: "57084",
            BookingURL: "https://bokning.mittvaccin.se/klinik/515/bokning"
        }
    ]
  }

  const server = setupServer(
    rest.get("http://localhost:8000/units", (req, res, ctx) => {
      return res(ctx.json(data.units))
    })
  )

  beforeAll(() => server.listen())
  afterEach(() => server.resetHandlers())
  afterAll(() => server.close())


  describe("<MunicipalityInfo />", () => {
    it("renders without crashing", async () => {
      render(<MunicipalityInfo />);
      const mainHeaderCity = await screen.findAllByRole("heading")
      const mapLink = await screen.findAllByTestId("map-link")
      const bookingLink = await screen.findAllByTestId("link-book-vaccination")

      expect(mainHeaderCity[0]).toHaveTextContent("Mörbylånga")
      expect(bookingLink[0]).toHaveTextContent("Boka tid för vaccination mot covid-19")
      expect(mapLink[0]).toHaveTextContent("Visa på karta")
      expect(mapLink.length).toBe(2);
      expect(bookingLink.length).toBe(2);
    })
  }) `

Component
`function MunicipalityInfo() {
  const [municipalityData, setMunicipalityData] = useState([])

  const fetchData = async () => {
    try{
      const result = await fetch("http://localhost:8000/units")
      const data = await result.json();
      setMunicipalityData(data)
    }catch(e){
      console.log(e)
    }
  }

  useEffect(() => {
    fetchData();
    setInterval(fetchData, 600000);
  }, []); 

  return(
    <>
      { municipalityData &&
        municipalityData.map((city, index) => {
          return (
            <Div key={index} data-testid="municipalityInfo-component" className="mt-5 p-3">
              <HeaderMain data-testid="header-main" id={city.City}>{city.City}</HeaderMain>
              <HeaderSub data-testid="header-sub" className="mt-4">{city.venamn}</HeaderSub>
              <BodyText data-testid="body-text">{city.Address}, {city.City}</BodyText>
              <MapLink href={"#"} data-testid="map-link"><i data-testid="map-icon" className="fas fa-map-marker-alt"></i> Visa på karta</MapLink>
              <LinkList data-testid="link-list">
                <LinkListItem data-testid="list-item-first">
                  <Link href={city.BookingURL} data-testid="link-book-vaccination">Boka tid för vaccination mot covid-19</Link>
                </LinkListItem>
              </LinkList>
              <Calendar data={city.unit}/>
            </Div>
          )
        })
      }
      <CitiesSideBar>
        <Sidebar data={municipalityData.cities}/>
      </CitiesSideBar>
    </>
  )
}

export default MunicipalityInfo;`

This passes like a charm!

But not when i use the XML file like in the example above.

**Comment by stavrosgemis** [comment] 2021-07-09 20:40
Actually the problem seems to be the ```js fetch(XMLFile)```

I use json server to make the test pass, it seems that the test passes if i use a "real" url.

```js
function MunicipalityInfo() {
  const [municipalityData, setMunicipalityData] = useState([])

  const fetchData = async () => {
    try{
      const result = await fetch("http://localhost:8000/units")
      const data = await result.json();
      setMunicipalityData(data)
    }catch(e){
      console.log(e)
    }
  }

  useEffect(() => {
    fetchData();
  }, []); 
  
---TEST---

``` js
  import { render, screen } from '@testing-library/react';
import MunicipalityInfo from './MunicipalityInfo';
import {setupServer} from 'msw/node';
import {rest} from 'msw';

  const server = setupServer(
    rest.get("http://localhost:8000/units", (req, res, ctx) => {
      return res(ctx.json(data.units))
    })
  )

  beforeAll(() => server.listen())
  afterEach(() => server.resetHandlers())
  afterAll(() => server.close())


  describe("<MunicipalityInfo />", () => {
    it("renders without crashing", async () => {
      render(<MunicipalityInfo />);
      const mapLink = await screen.findAllByTestId("map-link")
      const bookingLink = await screen.findAllByTestId("link-book-vaccination")



      expect(mapLink.length).toBe(2);
      expect(bookingLink.length).toBe(2);
    })
  }) 
```
When i use the XMLFile in my code i cant se that the dom nodes i the testcase is not being populated with values.

**Comment by MatanBobi** [comment] 2021-07-14 17:38
This might be a workaround but I don't see a reason to use native `fetch` in your test so I'd probably mock it in my tests using `[msw](https://mswjs.io/)` or any other fetch mock approach. Besides that, keep in mind that the `fetch` running is the `node`'s version `fetch` and not a browser (since node is running your tests).
If you do want to use `fetch`, you can try and use a polyfill for that.

**Comment by stavrosgemis** [comment] 2021-07-15 07:17
> This might be a workaround but I don't see a reason to use native `fetch` in your test so I'd probably mock it in my tests using [`msw`](https://mswjs.io/) or any other fetch mock approach.
> Besides that, keep in mind that the `fetch` running is the `node`'s version `fetch` and not a browser (since node is running your tests).
> If you do want to use `fetch`, you can try and use a polyfill for that.

Actually i use `msw` this is my code:
```import { render, screen } from '@testing-library/react';
import MunicipalityInfo from './MunicipalityInfo';
import {setupServer} from 'msw/node';
import {rest} from 'msw';

const data = {
    units: [
          {
            BookingURL: "https://thelink1.com"
        },
        {
            BookingURL: "https://thelink2.com"
        }
    ]
  }

       // I got the following wraning:
      //   [MSW] Warning: captured a request without a matching request handler:
     // • GET http://localhost/data.xml
    // But when i go to that url i dont see the XML file in my browser
   // If i go to the url src/xml/data.xml the i can see the XML file in the browser but i still get the same error in my test

  const server = setupServer(
    rest.get("http://localhost/src/data.xml", (req, res, ctx) => {
      return res(ctx.json(data.units));
    })
  )

  beforeAll(() => server.listen());
  afterEach(() => server.resetHandlers());
  afterAll(() => server.close());
  
  beforeEach(() => {
    render(<MunicipalityInfo />);
  })


  describe("<MunicipalityInfo />", () => {
    it("renders without crashing", async () => {
      const the_component = await screen.findByTestId("municipalityInfo-component");
      
      expect(the_component).toBeInTheDocument();
    })

    it("render with the correct elements and values", async() => {
        const mapLink = await screen.findAllByTestId("map-link");
        const bookingLink = await screen.findAllByTestId("link-book-vaccination");

        expect(mapLink.length).toBe(2);
        expect(bookingLink.length).toBe(2);
    })
  }) ```

**Comment by eps1lon** [comment] 2022-04-13 13:36
It doesn't look like this bug report has enough info for one of us to reproduce it.

Please provide a CodeSandbox or a link to a repository on GitHub.

Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by eps1lon** [comment] 2022-05-21 05:49
Closing since this looks more like a usage question that's best asked on https://testing-library.com/discord.

**Closed by eps1lon** 2022-05-21 05:49 UTC
Labels: needs more information
