### ISSUE TITLE
Printing lots of ReferenceError messages at the end of Jest test execution

### ISSUE THREAD

**Issue by Chris-Thompson-bnsf** [testing-library/react-testing-library#876] opened 2021-02-09 17:02 UTC
- `@testing-library/react` version: `11.2.3`
- Testing Framework and version:
Jest `26.6.0`, as part of Create-React-App v `4.0.2`
- DOM Environment:
jsdom `16.4.0`
Some other possibly relevant env stuff:
- React `17.0.1`
- Node `12.18.3`
- npm `7.5.2`
- TypeScript `4.1.2`

### Relevant code or config:
//MyComponent.tsx
```tsx
import * as React from 'react';
import { useMemo } from 'react';
import styles from './MyComponent.module.css';

export interface IMyComponentProps {
    originCity: string | null;
    originState: string | null;
    destinationCity: string | null;
    destinationState: string | null;
    showHeader?: boolean;
}

const MyComponent: React.FC<IMyComponentProps> = (props) => {
    const {
        originCity,
        originState,
        destinationCity,
        destinationState,
        showHeader,
    } = props;

    const lane = useMemo(() => {
        return `${originCity}, ${originState} to ${destinationCity}, ${destinationState}`;
    }, [destinationCity, destinationState, originCity, originState]);

    return (
        <>
            {showHeader && (
                <div>
                    <h5>MyComponent</h5>
                </div>
            )}
            <div className={styles.textGray}>{lane}</div>
        </>
    );
};

export default MyComponent;
```
//MyComponent.test.tsx
```tsx
import React from 'react';
import { shallow } from 'enzyme'; //used by some other tests in this file
import ReactDOM from 'react-dom'; //used by some other tests in this file
import MyComponent, { IMyComponentProps } from './MyComponent';
import { render, screen } from '@testing-library/react';

const getDefaultProps = (): IMyComponentProps => ({
    destinationCity: 'city1',
    destinationState: 'OH',
    originCity: 'city2',
    originState: 'CA',
    showHeader: true,
});

type TestCase = [string, string, string, string];

const TestCases: TestCase[] = [
	['city1', 'OH', 'city2', 'CA'],
];

it.each<TestCase>(TestCases)(
  'MyComponentshould display header text when showHeader is true',
  (originCity, originState, destinationCity, destinationState) => {
    //arrange
    const props = getDefaultProps();
    const expected = `${originCity}, ${originState} to ${destinationCity}, ${destinationState}`;

    //act
    render(<MyComponent{...props} />);
    const text = screen.findByText(expected);

    //assert
    expect(text).toBeDefined();
  },
);
```

### What you did:
`npm test -- "MyComponent.test"`

### What happened:
Jest run succeeds, but these lines are repeated many times (more than I can view in the VS Code terminal):
```
ReferenceError: You are trying to access a property or method of the Jest environment after it has been torn down.

      at node_modules/@testing-library/dom/dist/wait-for.js:67:14
```

Additional jest output:
```
A worker process has failed to exit gracefully and has been force exited. This is likely caused by tests leaking due to improper teardown. Try running with --detectOpenHandles to find leaks.
Test Suites: 1 passed, 1 total
Tests:       8 passed, 8 total
Snapshots:   0 total
Time:        12.431 s
Ran all test suites matching /MyComponent/i.
```

### Problem description:
This amount of output completely prevents seeing test failure messages, and also implies an issue with the code but does not make it clear where the issue lies.

### Suggested solution:
Besides identifying and fixing the underlying cause for this message (which may well be in the component/test code itself), the only thing I would suggest is to ensure that this message is only printed once, so as not to potentially hide other, more useful test output, such as test failures.

**Comment by afontcu** [comment] 2021-02-09 17:42
Hi,

`findByText` returns a promise, so you need to `await` it. The error logged in the terminal kinda points to that direction

**Comment by Chris-Thompson-bnsf** [comment] 2021-02-09 18:20
Thanks @afontcu , I switched over to use `getByText` in this case, and that did get rid of these messages.

However, interestingly enough, there was another test in this file that was using `findByText` without an `await`, but it was not causing any messages even before I this test to also use `getByText`:
```tsx
it('MyComponent should display header text when showHeader is true', () => {
	//arrange
	const props = getDefaultProps();
        props.showHeader = true;

	//act
	render(<MyComponent {...props} />);
	const text = screen.findByText('MyComponent');

	//assert
	expect(text).toBeDefined();
});
```

The primary difference between the two tests being that one was data-driven using `it.each` while the other was just a simple test using `it`.

**Comment by zeckdude** [comment] 2021-02-10 18:17
I am experiencing the same issue where I am seeing the same `ReferenceError` repeat forever until it crashes. I'm not actually using the `findByText` method though, so the proposed solution doesn't apply. 

> "@testing-library/jest-dom": "^5.11.9",
    "@testing-library/react": "^11.2.3",
    "@testing-library/user-event": "^12.6.3",

```js
import { render, waitFor } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { MockedProvider } from '@apollo/client/testing';

import TestWrapper from '../../lib/test-utils/TestWrapper';
import SignInPage from '../sign-in';
import GraphQLMutations from '../../networking/graphqlMutations';
import * as AnalyticsHelpers from '../../helpers/analytics';
import { Events } from '../../constants/events';

describe('Sign In Page', () => {
  const email = 'email@email.com';
  const password = 'password';

  const trackEventStub = jest.spyOn(AnalyticsHelpers, 'trackEvent').mockImplementation(() => {});

  const mocks = [
    {
      request: {
        query: GraphQLMutations.LOG_IN,
        variables: { email, password },
      },
      result: { data: { signIn: { id: 'abc123' } } },
    },
  ];

  test('should allow me to sign in', async () => {
    const wrapper = render(
      <MockedProvider mocks={mocks}>
        <TestWrapper>
          <SignInPage />
        </TestWrapper>
      </MockedProvider>,
    );

    expect(trackEventStub).toHaveBeenCalledTimes(1);
    expect(trackEventStub).toHaveBeenCalledWith({
      name: Events.LoginScreenViewed,
    });

    const emailInput = wrapper.getByTestId('email');
    const passwordInput = wrapper.getByTestId('password');
    const logInButton = wrapper.getByRole('button', { name: 'Log In' });

    userEvent.type(emailInput, email);
    userEvent.type(passwordInput, password);
    userEvent.click(logInButton);

    await waitFor(() => expect(trackEventStub).toHaveBeenCalledTimes(2));
  });
});
```

After the login button is clicked, a function is run that awaits a graphQL mutation to the server. Therefore, I need the `waitFor` to determine when the `trackEvent` method is called after the graphQL mutation completes. When I remove the `waitFor` line, I don't get the `ReferenceError` message, but I need it to determine when my stub has been called.

Having that `ReferenceError` all over the terminal makes it hard to read any other messages that are needed. Any suggestions on how to deal with my situation or is there a bug that needs to be fixed?

**Comment by MatanBobi** [comment] 2021-02-15 14:15
Hi @zeckdude! Since `waitFor` is async and jest has a default timeout, it seems as though the jest test timeout was exceeded, would you mind trying to extend it for that specific test and see if it helps?
To do that you'll need to add a second argument to `test` with the number (you can try 20000 for 20 seconds).
If this won't help, it means that the `expect` you're trying to assert didn't happen in a reasonable time IMO..

**Comment by eps1lon** [comment] 2021-06-02 10:15
It doesn't look like this bug report has enough info for one of us to reproduce it.

Please provide a CodeSandbox (https://react.new), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem. 

Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

Note that we'll close this issue if no reproduction will be provided. It's neccessary for us to have config, source, and test to debug this issue.

**Closed** 2022-04-13 13:35 UTC
Labels: question
