### ISSUE TITLE
Allow `renderHook` re-renders to passes down the new props to the wrapper.

### ISSUE THREAD

**Issue by messaooudi** [testing-library/react-testing-library#1163] opened 2022-12-16 08:53 UTC
When migrating our code base from @testing-library/react-hooks, we noticed that when re-rendering a hook the new props are not passed down to the wrapper component, which was the case before.
Passing props down to the wrapper component on re-renders allows us to test hooks that derive their logic from some context values.

**Comment by eps1lon** [comment] 2022-12-23 13:08
This was an intended change. Passing the props to the wrapper and hooks just makes it needlessly hard to track where props go. Especially from a types perspective.

Duplicate of https://github.com/testing-library/testing-library-docs/issues/1161

**Closed by eps1lon** 2022-12-23 13:08 UTC
