### ISSUE TITLE
Simulate fast-refresh

### ISSUE THREAD

**Issue by smmoosavi** [testing-library/react-testing-library#849] opened 2020-12-11 10:27 UTC
### Simulate fast-refresh

Recently fast-refresh introduced to react and used in create-react-app by default. I need to test what will happen when fast-refresh changes codes. This feature is required for state management libraries like `mobx`, `recoil`, `react-wire`.

[real-world code][code] that isn't testable without fast-refresh simulation

### Suggested implementation:

Suggested API:

```tsx
it('should refresh', () => {
  const fn = jest.fn();
  const useV1 = refreshable(() => {
    useEffect(() => {
      fn(1);
    }, []);
    return 5;
  });
  const useV2 = () => {
    useEffect(() => {
      fn(2);
    }, []);
    return 6;
  };
  const { result } = renderHook(() => {
    useV1();
  });
  act(() => {
    // somehow simulate fast-refresh reload
    useV1.refresh(useV2);
  });
  expect(result.current).toBe(6)
  expect(fn).toBeCalledWith(2);
});
```

[code]: https://github.com/forminator/react-wire/pull/31/files#diff-cd0f73f000c8ded0b19f569ae5821e62d4d07efcc4b9c0b0b69a18caf9e7113bR25-R32

**Comment by eps1lon** [comment] 2020-12-11 11:20
Could you clarify why there isn't an issue with fast-refresh i.e. what React core members think about this? As far as I can tell react-refresh is an implementation detail of hot-reloading and not something we should write "again". 

From what I can tell the code is problematic for another reason: It doesn't declare the dependencies of the hook which is probably why you're having issues.

**Comment by smmoosavi** [comment] 2020-12-11 18:35
> Could you clarify why there isn't an issue with fast-refresh 

Some situations happened when a fast-refresh update applied (as expected), but there is no way to create similar situations in the test environment. e.g., effects rerun as intended without changes in dependencies.

> As far as I can tell react-refresh is an implementation detail of hot-reloading and not something we should write "again".

I don't mean to rewrite fast-refresh but somehow test it. Maybe I should change "Simulate" to "Test" in the title.

> It doesn't declare the dependencies of the hook which is probably why you're having issues.

No, it's intentional. The code is only for supporting fast-refresh. The code inside the effect only should be run on a fast-refresh update.

**Comment by smmoosavi** [comment] 2020-12-11 18:51
This file contains tests for react-refresh itself

https://github.com/facebook/react/blob/master/packages/react-refresh/src/__tests__/ReactFresh-test.js

**Comment by eps1lon** [comment] 2020-12-11 20:24
> This file contains tests for react-refresh itself
> 
> [https://github.com/facebook/react/blob/master/packages/react-refresh/src/__tests__/ReactFresh-test.js](https://github.com/facebook/react/blob/master/packages/react-refresh/src/__tests__/ReactFresh-test.js?rgh-link-date=2020-12-11T18%3A51%3A03Z)

it would help a lot if you would apply that approach to your codebase first and then report back with your findings. A separate library would probably make the most sense here (like `@testing-library/hooks`). Once it has gained popularity and stabilized we can discuss merging it into core.

**Comment by eps1lon** [comment] 2021-01-13 03:24
Coming back to this problem since I just encountered a bug report caused by Fast Refresh that was also caused by `React.StrictMode`. 

Maybe we don't need  another API and just recommend wrapping your tests in `React.StrictMode`? That's what we've been using in Material-UI for a year or so now. It helped us quite a bit in tracking down possible problems in concurrent mode and we now have the first bug that was also reproduced by Fast Refresh.

I also looked again at the originally included [real world code](https://github.com/forminator/react-wire/pull/31/files#diff-cd0f73f000c8ded0b19f569ae5821e62d4d07efcc4b9c0b0b69a18caf9e7113bR25-R32) and it seems to me that the test for that is already ignored with `// eslint-disable-next-line` which ignores the exhaustive deps rule. 

I'm not sure a separate test API would actually help if we already have `React.StrictMode` and `eslint-plugin-react-hooks` that cover almost all cases. Especially since I'm not aware of any library we could use to simulate Fast Refresh.

**Comment by eps1lon** [comment] 2021-06-02 09:48
Closing since this issue hasn't received any updates and doesn't seem to be popular.

Right now you can partially test this with `React.StrictMode` and [`eslint-plugin-react-hooks`](https://www.npmjs.com/package/eslint-plugin-react-hooks). For more advanced scenarios it's better to copy the relevant parts of the [React FastRefresh test suite](https://github.com/facebook/react/blob/master/packages/react-refresh/src/__tests__/ReactFresh-test.js) In the future [React StrictEffects](https://github.com/facebook/react/pull/19523) may improve test coverage.

**Closed by eps1lon** 2021-06-02 09:48 UTC
Labels: needs investigation

**Comment by eps1lon** [comment] 2021-06-20 16:49
One final note: `React.StrictMode` will help test compatiblity with fast-refresh in React 18 since fast-refresh relies on the same constraints [Strict Effects](https://github.com/reactwg/react-18/discussions/19) will have.

So simulating fast-refresh will be as simple as wrapping your tested component in StrictMode in React 18: `render(<React.StrictMode><Component /></React.StrictMode>)`.

**Comment by ksandin** [comment] 2023-08-04 23:37
I needed to do this today and found this topic. Since there's no documentation for how to unit test react refresh, I followed @eps1lon's advice and checked out the react-refresh test suite. Took me a while to figure the ins and outs of it, but I managed to make it work eventually, even while using testing-library (the react-refresh test suite was not using testing-library).

Sharing my work in case someone else needs to do this in the future:
https://github.com/ksandin/yas/blob/master/packages/react-composable-form/src/__test__/reactFastRefresh.test.tsx

My key takeaways: 

1. Using react-refresh/runtime is brittle, since you need to be intimately aware with how react-refresh actually utilizes the runtime functions. If you do not mimic how its used in various bundlers in your test, then you will get false positives (or negatives). I stuggled with this a lot until I got it to work. 
2. Taking 1 into consideration: Make sure you call RefreshRuntime.register for each component in the component tree that you pass to testing-library/render, not just the root component. It was not clear to me that this was a requirement when I looked through the react-refresh test suite, but I learned that this is how react-refresh works by booting up vite with react and testing a number of fast refreshes and inspecting the network tab in my dev tools to see the actual javascript looked like that was being sent on each update. Then I could observe that indeed every component in the updated module got picked up by react-refresh and had its own RefreshRuntime.register call.

I only needed a few simple tests, so using react-refresh/runtime in jest was a good trade-off for me. But I was playing around with the idea of using playwright instead and literally run a vite dev server with react-refresh enabled, and have my tests actually emulate the developer process by making code changes to the files being served by vite, and trigger fast refresh that way instead. That approach would avoid needing to replicate the implementation details of react-refresh and make the tests way less brittle. If I were to do this whole thing again, or if I needed to write a much larget test suite, I'd probably try the playwright approach instead.
