### ISSUE TITLE
Complex Example error: window.fetch is not a function

### ISSUE THREAD

**Issue by pqr** [testing-library/react-testing-library#914] opened 2021-05-19 16:24 UTC
I've tried to run "Complex Example" described in README: https://github.com/testing-library/react-testing-library#complex-example

and got an error: "window.fetch is not a function".

Do I need to install some additional library "node-fetch" or "jest-mock-fetch" to make windoe.fetch function available on node environment when I am running tests?

**Comment by MatanBobi** [comment] 2021-05-23 08:52
Hi @pqr! Thanks for opening this one.
I'm not 100% sure but I think `jsdom` polyfills fetch. Can you please attach your testing environment? 
Running as node environment without having a window is problematic because we need a window to be defined :)

**Comment by eps1lon** [comment] 2021-06-02 10:24
Closing since no reproduction was provided. 

If the issue persists please open a new issue and follow the issue template. Config, source and test are necessary for us to be able to debug this issue.

**Closed by eps1lon** 2021-06-02 10:24 UTC
