### ISSUE TITLE
Jest 28 Issue

### ISSUE THREAD

**Issue by The-Code-Monkey** [testing-library/react-testing-library#1060] opened 2022-04-30 14:42 UTC
- `@testing-library/react` version: 13.1.1
- Testing Framework and version: Jest@28 with ts-jest and esm
- DOM Environment: jsdom@28.0.2

### Relevant code or config:

```js
import {
  render,
  waitFor,
  screen,
} from '@testing-library/react';
import * as React from 'react';

import Icon from '../Icon.js';

describe('<Icon />', () => {
  it('renders correctly', async () => {
    const { asFragment } = render(<Icon name='check' />);

    expect(asFragment()).toMatchSnapshot();

    await waitFor(() => expect(screen.getByTitle('check-icon')));

    expect(asFragment()).toMatchSnapshot();
  });
});

```

### What you did:

I updated to Jest@28 and type: "module" in package json

### What happened:

```
$ cross-env NODE_OPTIONS=--experimental-vm-modules tcm test
(node:41249) ExperimentalWarning: VM Modules is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
 FAIL  src/__test__/Icon.test.tsx
  ● Test suite failed to run

    ReferenceError: exports is not defined

      1 | import {
    > 2 |   render,
        |                    ^
      3 |   waitFor,
      4 |   screen,
      5 | } from '@testing-library/react';

      at src/__test__/Icon.test.tsx:2:23
      at TestScheduler.scheduleTests (../../node_modules/@jest/core/build/TestScheduler.js:317:13)
      at runJest (../../node_modules/@jest/core/build/runJest.js:407:19)
      at _run10000 (../../node_modules/@jest/core/build/cli/index.js:338:7)
      at runCLI (../../node_modules/@jest/core/build/cli/index.js:190:3)

```

### Reproduction:
https://github.com/The-Code-Monkey/TechStack/pull/299 -> packages/react-feather

### Problem description:

Fails the test

Edit: here is a link to the repo, the package that is failing first is packages/react-feather

https://github.com/The-Code-Monkey/TechStack

**Comment by The-Code-Monkey** [comment] 2022-04-30 18:29
tcm is just a cli wrapper that I have so it handles a few different commands e.g. linting and testing. I have confirmed that the cli works by having tests for the cli in the package.

**Comment by eps1lon** [comment] 2022-05-21 05:45
This looks more like an issue with your setup considering it's pulling in CommonJS when it seems like you want ES Modules. 

Could you create a minimal reproduction? The linked repository is fairly large and will make it hard to debug.

**Comment by eps1lon** [comment] 2022-08-04 16:51
Closing since to reproduction was provided

**Closed by eps1lon** 2022-08-04 16:51 UTC
Labels: needs more information
