### ISSUE TITLE
`RenderHookResult` doesn't match return value of `renderHook`

### ISSUE THREAD

**Issue by mattbrandlysonos** [testing-library/react-testing-library#1113] opened 2022-08-22 15:09 UTC
- `@testing-library/react` version: 13.3.0
- Testing Framework and version: jest@26.6.3
- DOM Environment: jsdom

### Relevant code or config:

If I write a small `renderHook` test and log the `result.current` value immediately after calling `renderHook`, this will show that the value is `null`.

```js
const { result } = renderHook(() => useMyHook())
console.log(result.current) // => null
```

According to the provided `RenderHookResult` type, that value should be of type `Result`, but `null` is not a valid instance of type `Result`.

https://github.com/testing-library/react-testing-library/blob/c80809a956b0b9f3289c4a6fa8b5e8cc72d6ef6d/types/index.d.ts#L101-L114

### Suggested solution:

Either the type could be updated:

```tsx
current: Result | null
```

Or the `renderHook` implementation could change such that it synchronously returns a value of type `Result`.

**Comment by eps1lon** [comment] 2022-09-04 16:49
It doesn't look like this bug report has enough info for one of us to reproduce it.

Please provide a CodeSandbox (https://react.new), or a link to a repository on GitHub.

Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by ntucker** [comment] 2023-01-06 11:52
This happens if there's an act call within the hook call stack

**Comment by eps1lon** [comment] 2023-01-07 14:08
@ntucker Calling `act` within a hook is a bit odd considering `act` is a testing utility. It doesn't even work in production.

I'll try to figure out why it behaves at runtime like this. Ideally, we'd warn about it I think. 


Could you elaborate why you're using `act` inside a hook?

**Comment by ntucker** [comment] 2023-01-07 14:11
> Could you elaborate why you're using `act` inside a hook?

Async callstack (say a network response) triggering setstate. Since it's async the test itself cannot be inlining the act call

**Comment by eps1lon** [comment] 2023-01-07 14:16
Could you give a complete example for this? I don't really see why the nested `act` is required as opposed to waiting with e.g. `waitFor`

**Comment by ntucker** [comment] 2023-01-07 15:31
According to https://reactjs.org/docs/test-utils.html#act it "This makes your test run closer to how React works in the browser." I don't really know what that means, but I assume that means it flushes the macro task buffer for batched renders. Without it the react updates don't happen.

**Comment by eps1lon** [comment] 2023-02-16 17:15
Closing since this is unrelated to types and you don't need to run `act` inside hooks (since it's a dev-only tool).

**Closed by eps1lon** 2023-02-16 17:15 UTC
Labels: needs more information
