### ISSUE TITLE
FakeTimes problem when upgrading jest 25 to 29

### ISSUE THREAD

**Issue by Okyaaa** [testing-library/react-testing-library#1161] opened 2022-12-08 08:03 UTC
Hi, everyone! I have several problems when upgrading jest 25 to 29
(Problem on faketimers)

 Installed dependencies

"react": "16.13.1",
"react-dom": "16.13.1",

"@testing-library/react-hooks": "^7.0.2",
"@testing-library/jest-dom": "5.16.5",
"@testing-library/react": "12.1.5",
"@types/jest": "28.1.1",
"@types/react": "^17.0.33",
"jest": "29.2.2",
"jest-environment-jsdom": "^29.2.2",
"jest-junit": "^12.0.0", 
"typescript": "4.3"

Jest.config
![image](https://user-images.githubusercontent.com/62287434/206391617-92e27ae3-425e-44e0-9d26-af538b6f6ca2.png)

When using fake timers i have to set legacy to true and the advanceTimers going to works, but it's not work in another test
Example :

![image](https://user-images.githubusercontent.com/62287434/206391262-11aca584-a7f5-4cd9-8bb2-34e1a0d55dd9.png)
On this code advanceTimers not works fine, at some cases there are a few tests that we need to raise the timeout duration, is there any explanation or something ?

![image](https://user-images.githubusercontent.com/62287434/206391301-7fe4e4bb-83b5-42d5-9eee-7dfdfe249a28.png)
If you have any suggestions for my problem, it's going to help me a lot. Thank you

**Comment by Okyaaa** [comment] 2022-12-08 08:06
Installed depedencies

"react": "16.13.1",
"react-dom": "16.13.1",

"@testing-library/react-hooks": "^7.0.2",
"@testing-library/jest-dom": "5.16.5",
"@testing-library/react": "12.1.5",
"@types/jest": "28.1.1",
"@types/react": "^17.0.33",
"jest": "29.2.2",
"jest-environment-jsdom": "^29.2.2",
"jest-junit": "^12.0.0", 
"typescript": "4.3"

Jest.config
![image](https://user-images.githubusercontent.com/62287434/206392661-cfd81b4f-6dcd-4f77-a47e-52c6f25525e9.png)


Hii, everyone! I have several problem when uprading jest 25 to 29
(Problem on faketimers)
When using fake timers i have to set legacy to true and the advanceTimers gonna works, but its not work in other test
Example :
![image](https://user-images.githubusercontent.com/62287434/206392494-56934c99-9052-4a18-b6b0-f2529e297298.png)
On this code advanceTimers not works fine, at some cases there is a few test that we need to raise the timeout duration, is there any explanation or something ?

![image](https://user-images.githubusercontent.com/62287434/206392570-107a70bc-9149-4d71-a659-0c8ef3a6ad18.png)
If you have any suggestion from my problem, its gonna help me a lot. Thank you

**Comment by compulim** [comment] 2023-01-26 07:45
Same to me.

I tested it against the official sample "Scenario 5: setTimeout" from https://react-testing-library-examples.netlify.app/. It appears the `jest.runAllTimers()` did not advance the clock.

**Comment by deshiknaves** [comment] 2023-01-27 15:38
Except using `jest.userRealTimers` means that now the test takes longer to run.

**Comment by eps1lon** [comment] 2023-02-15 20:15
It doesn't look like this bug report has enough info for one of us to reproduce it.

Please provide a CodeSandbox (https://react.new), or a link to a repository on GitHub.

Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by eps1lon** [comment] 2023-05-22 15:21
Closing since no repro was provided.

**Closed by eps1lon** 2023-05-22 15:21 UTC
Labels: needs more information
