### ISSUE TITLE
useContext return null

### ISSUE THREAD

**Issue by xiaokesong** [testing-library/react-testing-library#1179] opened 2023-02-19 09:24 UTC
- `@testing-library/react` version:13.4.0
- Testing Framework and version:"jest": "28.1.1"
  
- DOM Environment:jest-environment-jsdom@28.1.1
- System:Window 10

### Relevant code or config:
```
it('should render a loading-button', () => {
      const buttonText = 'Hello World';
      const cb = jest.fn();
      const { getByRole } = render(
        <DButton dLoading={true} onClick={cb}>
          {buttonText}
        </DButton>
      );
      const button = getByRole('button');
      expect(button.className.includes('is-loading')).toBe(true);
      expect(button.querySelector(`.${dPrefix}button__icon`)).toBeInTheDocument();
      fireEvent.click(button);
      expect(cb).not.toBeCalled();
    });
```

### What you did:
In DButton component useContext(DIconContext) not return null,
but in DButton child Icon component useContext(DIconContext) return null
And in mac system is correct

**Comment by MatanBobi** [comment] 2023-02-19 09:31
Hi @xiaokesong, thanks for opening this one.
Unfortunately, this issue doesn't have enough for us to investigate it.
Can you please create a minimal reproduction either in a github repo / codesandbox so we'll be able to look into it?
Having said that, I don't think that the OS is the issue here. Did you wrap your component with a `ContextProvider`? Since we don't know what's the implementation of `DButton`, we can't know what's happening there.

**Comment by xiaokesong** [comment] 2023-02-19 09:36
> Hi @xiaokesong, thanks for opening this one. Unfortunately, this issue doesn't have enough for us to investigate it. Can you please create a minimal reproduction either in a github repo / codesandbox so we'll be able to look into it? Having said that, I don't think that the OS is the issue here. Did you wrap your component with a `ContextProvider`? Since we don't know what's the implementation of `DButton`, we can't know what's happening there.

github repo: https://github.com/xiaokesong/react-devui/tree/main
in windows system
init: yarn
test:nx run ui:test
and then you will find error

**Comment by xiejay97** [comment] 2023-02-22 07:31
@MatanBobi I also test it, the context miss in windows(22621.1265), but github action is ok that the env is ubuntu.

https://github.com/DevCloudFE/react-devui/actions/runs/4199855774/jobs/7285241384

**Comment by MatanBobi** [comment] 2023-02-22 07:34
@xiaokesong @xiejay97 Since I don't have a windows machine, I'll have to defer to someone else to investigate this.
Also,  a minimal reproduction will be more helpful. Installing a bunch of dependencies will only make it harder for us to understand if there's an issue with testing-library.

**Comment by xiejay97** [comment] 2023-02-22 07:35
@MatanBobi I will give a minimal reproduction, thanks for your job

**Comment by xiejay97** [comment] 2023-02-22 09:08
@MatanBobi Hi, I test with only `react` and `@testing-library`, and it's ok both windows and ubuntu. It seems to be some other reason, sorry for taking you extra time.

**Comment by MatanBobi** [comment] 2023-02-22 10:00
Thanks @xiejay97  :)
@xiaokesong can we close this one?

**Closed** 2023-02-22 12:13 UTC
Labels: needs more information
