### ISSUE TITLE
using computedStyleSupportsPseudoElements:false force me to cleanup afterEach manually

### ISSUE THREAD

**Issue by nsaubi** [testing-library/react-testing-library#984] opened 2021-10-22 11:00 UTC
**Describe the bug**

cleanup seems not to be automatically called in afterEach when using computedStyleSupportsPseudoElements:false.

**To Reproduce**

1. you need to have the computedStyle warning from jsdom... (I don't really know how to reproduce)
2. add `computedStyleSupportsPseudoElements:false` in your test configuration
3. now run a test with multiple it('....', ()=>{}) rendering your component
4. you should have an error if you use a screen.getByText (or anything that waits a single result), as DOM will concat on each render and have multiple times your component

**Expected behavior** 

cleanup should be called after each 'it()'

**Desktop (please complete the following information):**

- OS: Ubuntu 20.04.3 LTS
- Browser: chrome
- Version: 94.0.4606.81

**Additional context**

I was fighting with the computedStyle warning that appeared with jsdom lib.
My tests were passing, but with a lot of noise.

I finally updated my libs (testing-lib, jest, etc.) and still get the noise from jsdom. 
Then I found the `computedStyleSupportsPseudoElements:false` configuration option and the warning was gone. 
But, starting now, my tests were broken due to multiple instances found for my `screen.getByX` methods. It seemed the screen was not cleared after each renders, as my rendered dom was containing multiple instances of my tested components.
I tested adding manually `afterEach(()=>cleanup())` and it passed the test again.

**Comment by eps1lon** [comment] 2022-03-02 10:14
Closing since no reproduction was provided in 4 months.

**Closed by eps1lon** 2022-03-02 10:14 UTC
Labels: needs more information
