### ISSUE TITLE
WaitFor does not wait long enough

### ISSUE THREAD

**Issue by ss-nef** [testing-library/react-testing-library#899] opened 2021-04-13 08:18 UTC
- `@testing-library/react` version: "^11.2.3"
- Testing Framework and version:
 `jest` version: "^26.6.3"
- DOM Environment:
 `react-dom` version: "17.0.1"
 `@testing-library/jest-dom` version: "^5.11.9"

### Relevant code or config:

```js
    import { ROUTES } from "@company/app/features";
    import {
      fireEvent,
      MockedRouter,
      render,
      screen,
      waitFor,
    } from "@company/test-utils";
    import { tr } from "@company/utils/i18n";
    import { NextRouter } from "next/router";
    import { LoginPage } from "./Login.stories";
    
    describe("Login", () => {
      it("Loads Login and causes an error", async () => {
        const router: Partial<NextRouter> = {
          pathname: "/login",
          push: jest.fn(),
        };
        render(
          <MockedRouter router={router}>
            <LoginPage />
          </MockedRouter>
        );
    
        await screen.findByText(tr.LOGIN.TITLE);
        await screen.findByText(tr.LOGIN.BTN_LOGIN);
    
        const email = screen.getByPlaceholderText(tr.LOGIN.PLACEHOLDER_EMAIL);
        const password = screen.getByPlaceholderText(tr.LOGIN.PLACEHOLDER_PASSWORD);
    
        fireEvent.input(email, { target: { value: "info@abc.de" } });
        fireEvent.input(password, { target: { value: "wrong" } });
    
        const btn = screen.getByRole("button", { name: "Login" });
        fireEvent.click(btn);
    
        await waitFor(() => {
          expect(screen.getByText(tr.LOGIN.BTN_LOGIN_LOADING)).toBeVisible()
        })
        await waitFor(() => {
          expect(screen.getByText("Email oder Passwort sind falsch.")).toBeVisible();
        });
      });
    });
```

### What you did:

I am trying to test the appearance of an error message. When I test the page in the browser, I fill in the email and password, click on "Login" and after half a second there is a login error message. 

### What happened:

When I use this test, the last waitFor will cause the following error:
```
TestingLibraryElementError: Unable to find an element with the text: Email oder Passwort sind falsch.. This could be because 
the text is broken up by multiple elements. In this case, you can provide a function for your text matcher to make your 
matcher more flexible.
```

The state of the dom is this:
```html
<body
      class="chakra-ui-light"
    >
      <div
        id="chakra-toast-portal"
      >
        <ul
          id="chakra-toast-manager-top"
          style="position: fixed; z-index: 5500; pointer-events: none; display: flex; flex-direction: column; margin: 0px auto; top: 0px; right: 0px; left: 0px;"
        />
        <ul
          id="chakra-toast-manager-top-left"
          style="position: fixed; z-index: 5500; pointer-events: none; display: flex; flex-direction: column; top: 0px; left: 0px;"
        />
        <ul
          id="chakra-toast-manager-top-right"
          style="position: fixed; z-index: 5500; pointer-events: none; display: flex; flex-direction: column; top: 0px; right: 0px;"
        />
        <ul
          id="chakra-toast-manager-bottom-left"
          style="position: fixed; z-index: 5500; pointer-events: none; display: flex; flex-direction: column; bottom: 0px; left: 0px;"
        />
        <ul
          id="chakra-toast-manager-bottom"
          style="position: fixed; z-index: 5500; pointer-events: none; display: flex; flex-direction: column; margin: 0px auto; bottom: 0px; right: 0px; left: 0px;"
        />
        <ul
          id="chakra-toast-manager-bottom-right"
          style="position: fixed; z-index: 5500; pointer-events: none; display: flex; flex-direction: column; bottom: 0px; right: 0px;"
        />
      </div>
      <div>
        <div
          class="chakra-stack css-1556tol"
        >
          <h2
            class="chakra-heading css-1jb3vzl"
          >
            Login Daten
          </h2>
          <p
            class="chakra-text css-0"
          >
            For login error use password "wrong"
          </p>
        </div>
        <hr
          aria-orientation="horizontal"
          class="chakra-divider css-1nxdd8d"
          role="separator"
        />
        <div
          class="chakra-container css-1gnc5ed"
        >
          <div
            class="chakra-stack css-1fxxgjv"
          >
            <h2
              class="chakra-heading css-1jkx6l7"
            >
              Einloggen auf Company
            </h2>
            <form>
              <div
                class="chakra-stack css-qj1q0a"
              >
                <div
                  class="chakra-form-control css-1kxonj9"
                  role="group"
                >
                  <input
                    aria-describedby="field-1-helptext"
                    class="chakra-input css-gnca8l"
                    id="field-1"
                    name="email"
                    placeholder="ihr-name@firma.de"
                  />
                  <div
                    class="chakra-form__helper-text css-1ucnah7"
                    id="field-1-helptext"
                  />
                </div>
                <div
                  class="chakra-form-control css-1kxonj9"
                  role="group"
                >
                  <div
                    class="chakra-input__group css-4302v8"
                  >
                    <input
                      aria-describedby="field-2-helptext"
                      autocomplete="on"
                      class="chakra-input css-1gwpi8i"
                      id="field-2"
                      name="password"
                      placeholder="Ihr Passwort"
                      type="password"
                    />
                    <div
                      class="chakra-input__right-element css-3so1kk"
                    >
                      <button
                        class="chakra-button css-15qn773"
                        type="button"
                      >
                        <svg
                          class="chakra-icon css-onkibi"
                          focusable="false"
                          viewBox="0 0 24 24"
                        >
                          <g
                            fill="currentColor"
                          >
                            <path
                              d="M23.432,10.524C20.787,7.614,16.4,4.538,12,4.6,7.6,4.537,3.213,7.615.568,10.524a2.211,2.211,0,0,0,0,2.948C3.182,16.351,7.507,19.4,11.839,19.4h.308c4.347,0,8.671-3.049,11.288-5.929A2.21,2.21,0,0,0,23.432,10.524ZM7.4,12A4.6,4.6,0,1,1,12,16.6,4.6,4.6,0,0,1,7.4,12Z"
                            />
                            <circle
                              cx="12"
                              cy="12"
                              r="2"
                            />
                          </g>
                        </svg>
                      </button>
                    </div>
                  </div>
                  <div
                    class="chakra-form__helper-text css-1ucnah7"
                    id="field-2-helptext"
                  />
                </div>
                <button
                  class="chakra-button css-ysjtt0"
                  data-loading=""
                  disabled=""
                  type="submit"
                >
                  <div
                    class="chakra-button__spinner css-149izd1"
                  >
                    <div
                      class="chakra-spinner css-1ojda53"
                    >
                      <span
                        class="css-f8n5zr"
                      >
                        Loading...
                      </span>
                    </div>
                  </div>
                  Sende Daten ...
                </button>
              </div>
            </form>
            <a
              class="chakra-link css-11ga3ac"
              href="/password-reset"
            >
              Passwort vergessen?
            </a>
          </div>
        </div>
      </div>
</body>
```

As you can see the loading message is in the dom, which is expected after clicking the login button. That is also the reason the first waitFor call works. But The login error message does not show up. It should show up like this:

```html
<div role="alert" class="chakra-alert css-w5gexa">
<span class="chakra-alert__icon css-19vbqnl">
<svg viewBox="0 0 24 24" focusable="false" class="chakra-icon css-fi0ww0"><path fill="currentColor" d="M11.983,0a12.206,12.206,0,0,0-8.51,3.653A11.8,11.8,0,0,0,0,12.207,11.779,11.779,0,0,0,11.8,24h.214A12.111,12.111,0,0,0,24,11.791h0A11.766,11.766,0,0,0,11.983,0ZM10.5,16.542a1.476,1.476,0,0,1,1.449-1.53h.027a1.527,1.527,0,0,1,1.523,1.47,1.475,1.475,0,0,1-1.449,1.53h-.027A1.529,1.529,0,0,1,10.5,16.542ZM11,12.5v-6a1,1,0,0,1,2,0v6a1,1,0,1,1-2,0Z">
</path></svg>
</span>Email oder Passwort sind falsch.</div>
```

### Reproduction:

I cant share much more code since most of it is proprietary. 

### Problem description:

I does not seem possible to test the appearance of an error message that takes some time to load. The waitFor function simply doesnt wait long enough.

### Suggested solution:

give more control to the wait time

**Comment by alex-james-vukovity** [comment] 2021-04-14 19:05
have you tried using `waitForElementToBeRemoved` instead of `waitFor` ?

```
 const btn = screen.getByRole("button", { name: "Login" });
 fireEvent.click(btn);
        
 waitForElementToBeRemoved(await findByText('Loading...'))
    
 expect(screen.getByText("Email oder Passwort sind falsch.")).toBeInTheDocument();
```

if this is still not long enough, you can always increase `timeout` like so
` waitForElementToBeRemoved(await findByText('Loading...')), { timeout: 5000 })` // default is 1000ms

you can pass `timeout` to `waitFor` and `findBy*` in the same way, as well

or you can increase it globally for all tests in your `setupTests` file like so
`configure({ asyncUtilTimeout: 5000 })`

https://testing-library.com/docs/dom-testing-library/api-async

**Comment by eps1lon** [comment] 2021-06-02 09:51
Closing this issue since it remained incomplete for too long. https://github.com/testing-library/react-testing-library/issues/899#issuecomment-819761678 seems to solve the issue at hand.

Without a complete reproduction, we can't debug the issue. For proprietary code I suggest you hire someone who signs an NDA. Free open source software is not the right avenue for these sorts of issues.

**Closed by eps1lon** 2021-06-02 09:51 UTC
