### ISSUE TITLE
Update the peer deps to the latest version

### ISSUE THREAD

**Issue by pedroSoaresll** [testing-library/react-testing-library#1076] opened 2022-05-23 16:27 UTC
### Describe the feature you'd like:
Change the react and react-dom to latest version in peer dependency. To the new version of npm can install normally `testing-library/react` without fail and suggest the use of `--legacy-peer-deps`

### Suggested implementation:

change the version in `package.json` to the latest from both

### Describe alternatives you've considered:

An alternative is to install the packages using `--legacy-peer-dependency`

**Comment by pedroSoaresll** [comment] 2022-05-23 16:52
@eps1lon is about it

![image](https://user-images.githubusercontent.com/11558773/169869577-c0661c74-34ef-480b-84d2-0dd7ee3480fb.png)

with the new npm version peer deps are automatically installed and if found some incoherence with the versions the installation fails warning about.

**Comment by eps1lon** [comment] 2022-05-23 17:49
This error doesn't make sense to me. `^18.0.0` is fulfilled by `18.1.0`. Do you have a cloneable repository and NPM version that reproduces this problem?

**Comment by jbradford** [comment] 2022-05-31 13:09
We had the same problem locally because we'd previously used `--legacy-peer-dependency` to resolve an issue like this, when I deleted the `package-lock.json` it revealed actual packages with problems which had previously been "fixed" using `--legacy-peer-depencency`.

**Comment by pedroSoaresll** [comment] 2022-06-03 19:43
> This error doesn't make sense to me. `^18.0.0` is fulfilled by `18.1.0`. Do you have a cloneable repository and NPM version that reproduces this problem?

I'll try to replicate the problem in a individual repo and share here mentioning you.

**Comment by LZL0** [comment] 2022-06-05 15:21
I am having the same issue with the exact same output as @pedroSoaresll.

**Comment by eps1lon** [comment] 2022-06-05 15:30
Do you maybe have packages in your dependency tree hat still require React 17?

**Comment by LZL0** [comment] 2022-06-05 21:42
Yes, but I am not getting a fatal error if I remove the React Testing Library from the package.json file.

**Comment by eps1lon** [comment] 2022-06-06 10:22
Without a cloneable repository and the NPM version we won't be able to debug this issue.

**Comment by morkro** [comment] 2022-06-11 10:40
I am getting the same error message, my dependency tree is:

```json
{
  "dependencies": {
    "react": "^18.1.0",
    "react-dom": "^18.1.0"
  },
  "devDependencies": {
    "@testing-library/react": "^13.3.0"
  }
}
```

**Comment by MatanBobi** [comment] 2022-06-12 08:39
@morkro are those the only dependencies you have? Can you please share a cloneable repo?

**Comment by Darkskittlz** [comment] 2022-06-18 15:52
I'm getting the same error here 

![Captures_6_18_2022_11_25_45_AM.png](https://user-images.githubusercontent.com/66503942/174446317-13bc66d6-afa9-4be7-a7f5-8da51e596594.png)

Package.json of cloneable Repo: https://github.com/Darkskittlz/BandingoModal/blob/main/package.json

**Comment by eps1lon** [comment] 2022-06-18 18:22
@Darkskittlz The shared package.json does not contain version 13. But the error you show uses version 13. So either some other dependency uses version 13 or your package.json changed in the meantime (please share a permalink).

But if something in your dependency tree is using version 13 then you need to get rid of it considering you're only using React 17

**Comment by Darkskittlz** [comment] 2022-06-18 23:17
thanks @eps1lon I've managed to clear out any dependencies that were conflicting with React 17 but I am now getting an error with setting up the edge functions environment.

![PowerShell 6_18_2022 7_16_22 PM](https://user-images.githubusercontent.com/66503942/174459846-a0bb7cb1-57c7-48c2-8f51-d84ed43e8bdc.png)

Command: node --trace-deprecation ...

![Update the peer deps to the latest version · Issue #1076 · testing-library_react-testing-library - Google Chrome 6_18_2022 7_17_10 PM](https://user-images.githubusercontent.com/66503942/174459873-4ed07bfb-a32c-4311-b344-45fe7999194d.png)

**Comment by eps1lon** [comment] 2022-06-19 11:00
I can't help you with these issues. This GitHub issue is specifically for "conflicting peer dependencies" with npm

**Comment by mbrevda** [comment] 2022-07-03 10:35
[Here](https://github.com/mbrevda/react-image) is a repo that seems to be suffering from this issue. When testing, please checkout a commit made prior to this message in case I change anything

**Comment by eps1lon** [comment] 2022-07-05 20:05
Closing since nobody is able to reproduce this with a minimal repository. Please understand that we don't have the bandwidth to debug full monorepos. For that please use https://testing-library.com/discord.

To understand how to create  minimal repro please read https://antfu.me/posts/why-reproductions-are-required#how-to-create-a-minimal-reproduction.

I'm going to close this since this issue is likely to pull in more unrelated reports regarding "conflicting peer dependencies".

**Closed by eps1lon** 2022-07-05 20:05 UTC
Labels: needs more information

**Comment by mbrevda** [comment] 2022-07-06 05:51
If you run `npm i` on the repo I linked to above you'll see the issue. Not sure how closing the issue solves it

**Comment by WesleyKapow** [comment] 2022-09-13 16:37
Hitting the same issue.

```
    "react": "^18.2.0",
    "@testing-library/react": "^13.4.0",
```
