### ISSUE TITLE
FireEvent not works after async test

### ISSUE THREAD

**Issue by alessandro308** [testing-library/react-testing-library#938] opened 2021-07-02 09:37 UTC
- `@testing-library/react` version: 11.2.7
- Testing Framework and version: React 17, Jest
- DOM Environment: jsdom 16.5.3, node v12.18.2

### Relevant code or config:

```js
import {render, screen, waitFor, fireEvent} from '@testing-library/react';
import React from 'react';

const Component = ({asyncClick, syncClick}) => {
    function onClick(){
        console.log('clicked');
        syncClick();
        setTimeout(() => {
            asyncClick();
        }, 50);
    }
    return <div data-testid="toBeClick" onClick={onClick}>

    </div>;
}

describe('a test', function(){
    it('element exists', function(){
        render(<Component/>);
        let el = screen.getByTestId('toBeClick');
        expect(el).toBeInTheDocument();
    });

    it('element Click', async function(){
        let syncClick = jest.fn();
        let asyncClick = jest.fn();
        render(<Component asyncClick={asyncClick} syncClick={syncClick} />);
        let el = screen.getByTestId('toBeClick');
        fireEvent.click(el);
        expect(syncClick).toHaveBeenCalledTimes(1);
        await waitFor(() => {
            expect(asyncClick).toHaveBeenCalledTimes(1);
        });

    });

    it('element Click / 2', async function(){
        let syncClick = jest.fn();
        let asyncClick = jest.fn();
        render(<Component asyncClick={asyncClick} syncClick={syncClick} />);
        let el = screen.getByTestId('toBeClick');
        fireEvent.click(el);
        expect(syncClick).toHaveBeenCalledTimes(1);
        await waitFor(() => {
            expect(asyncClick).toHaveBeenCalledTimes(1);
        });

    });

})
```

### Problem description:

Second test pass. Third test fails. It's the same test copy-and-pasted.
Removing Async/Await  and waitFor from the second one, the third test starts to pass.

**Comment by danieltorrer** [comment] 2021-07-09 16:30
Hi @alessandro308 , did you find a solution or a workaround for this?

**Comment by eps1lon** [comment] 2021-09-13 09:31
The pasted code is passing in a default Create React App `yarn create react-app` with 

```bash
$ npx testing-library-envinfo react
npx: installed 2 in 2.755s

  System:
    OS: Linux 5.4 Ubuntu 20.04.3 LTS (Focal Fossa)
  Binaries:
    Node: 12.22.6 - ~/.nvm/versions/node/v12.22.6/bin/node
    Yarn: 1.22.5 - /usr/bin/yarn
    npm: 6.14.15 - ~/.nvm/versions/node/v12.22.6/bin/npm
  npmPackages:
    @testing-library/dom:  7.31.2 
    @testing-library/jest-dom: ^5.11.4 => 5.14.1 
    @testing-library/react: ^11.1.0 => 11.2.7 
    @testing-library/user-event: ^12.1.10 => 12.8.3 
    aria-query:  4.2.2 
    dom-accessibility-api:  0.5.7 
    jest:  26.6.0 
    jsdom:  16.7.0 
    react: ^17.0.2 => 17.0.2 
    react-dom: ^17.0.2 => 17.0.2
```

as well as with the latest versions of `@testing-library/*` and Jest 27.

@alessandro308 Could you provide a minimal cloneable repository that reproduces the bug?

**Comment by alessandro308** [comment] 2021-09-13 09:36
@eps1lon Hi, I resolved the issue. It was specific of my environment. We are migrating an AngularJS app to React so our codes uses React, AngularJS and IonicV1. For some reason, importing ionic in the setup file prevents fireEvent in an async function. I haven't investigated much more but if you think can be useful, I can prepare a complete example with the issue

**Comment by eps1lon** [comment] 2021-09-13 09:42
> I haven't investigated much more but if you think can be useful, I can prepare a complete example with the issue

That may be helpful to future readers so that's always appreciated. Will close the issue though since it's not actionable for us. You can continue commenting with your example.

**Closed by eps1lon** 2021-09-13 09:42 UTC
Labels: needs more information
