### ISSUE TITLE
 TypeError: (0 , _dom.configure) is not a function

### ISSUE THREAD

**Issue by jonaohana** [testing-library/react-testing-library#1055] opened 2022-04-24 19:10 UTC
At a loss here, when I stepped through code, _dom is an object with many properties just not configure, version mismatch?
any help would be appreciated.

 FAIL  src/components/RewardForm/RewardForm.test.tsx
  ● Test suite failed to run

    TypeError: (0 , _dom.configure) is not a function

      1 | import React from 'react';
    > 2 | import { screen, render, getByTestId, fireEvent } from '@testing-library/react';
        | ^
      3 | import userEvent from '@testing-library/user-event';
      4 | import { useForm } from 'react-hook-form';
      5 | import '@testing-library/jest-dom';

**Comment by MatanBobi** [comment] 2022-04-24 19:14
Hi @jonaohana, at the moment this report doesn't have enough details for us to try and investigate it.
Please create a codesandbox reproduction of this issue and also state which versions you're currently using so we'll be able to try and help :)
Thanks.

**Comment by MatanBobi** [comment] 2022-05-06 21:26
Hi @Cayan.. Can you please provide a reproduction? We can't investigate this any further without a reproduction..
Thanks!

**Comment by Cayan** [comment] 2022-05-07 09:17
Hi @MatanBobi after a long investigation I was able to fix the problem!

Apparently, a `moduleNameMapper` for the `config` key was causing such conflict.

**Comment by rstevens354** [comment] 2022-05-11 07:24
> Hi @MatanBobi after a long investigation I was able to fix the problem!
> 
> Apparently, a `moduleNameMapper` for the `config` key was causing such conflict.

@MatanBobi could you let me know how you overcame this? i have the exact same problem

**Comment by rstevens354** [comment] 2022-05-11 07:26
@Cayan any chance you could let me know your fix? I have the exact same error caused by the same `moduleNameMapper` config

**Comment by MatanBobi** [comment] 2022-05-11 07:55
@rstevens354 you can share your `moduleNameMapper` here and we'll try to help with that :)
Anyways, I'm closing as it looks like this is not an issue with testing-library and the original poster didn't comment back with information, if you think it is, please comment here and we'll re-open.

Thanks @Cayan!

**Closed by MatanBobi** 2022-05-11 07:55 UTC
Labels: needs more information

**Comment by eps1lon** [comment] 2022-05-11 08:09
> Hi @MatanBobi after a long investigation I was able to fix the problem!
> 
> Apparently, a `moduleNameMapper` for the `config` key was causing such conflict.

We've had a similar report in the past that was fixed with https://github.com/testing-library/react-testing-library/issues/1064#issuecomment-1122354171
