### ISSUE TITLE
Event properties (e.g. button) are not passed to event handler in pointerDown event

### ISSUE THREAD

**Issue by szhsin** [testing-library/react-testing-library#838] opened 2020-11-28 10:43 UTC
- `@testing-library/react` version: 11.2.2
- Testing Framework and version: jest
  
- DOM Environment: jsdom
  

### Relevant code or config:

```jsx
const App = () => {
  const [isRightClick, setRightClick] = useState(false);

  const handlePointerDown = (e) => {
    console.log("e.button:", e.button);
    if (e.button === 2) setRightClick(true);
  };

  return (
    <div
      className={isRightClick ? "rightClick" : "noClick"}
      onPointerDown={handlePointerDown}
    >
      Right click me
    </div>
  );
};

test("Pointer down with right click", () => {
  render(<App />);

  const element = screen.queryByText("Right click me");
  expect(element).toHaveClass("noClick");
  fireEvent.pointerDown(element, { button: 2 });
  expect(element).toHaveClass("rightClick");
});
```

### What you did:

Fire `pointerDown` event with `button` property set to 2, simulating a right click.
### What happened:
In the event handler which handles the `onPointerDown` event, `e.button` is `undefined` instead of 2.

### Reproduction:

[Please see an Codesandbox example](https://codesandbox.io/s/testing-library-pointer-event-el6xt)

### Problem description:

Test always fails in components which handle right click events.

### Suggested solution:

Pass all event properties fired in `pointerDown` event to corresponding event handler.

**Comment by marcosvega91** [comment] 2020-11-28 17:26
Hi @szhsin thanks for reaching us 😄 

Unfortunately `pointerEvent` is not yet implemente in `jsdom`. There is an open PR of @eps1lon https://github.com/jsdom/jsdom/pull/2666.

As workaround you can provide your own implementation of `PointerEvent`

```js
class PointerEvent extends Event {
   constructor(type, props) {
     super(type, props)
     if (props.button != null) {
       this.button = props.button
     }
   }
 }
 window.PointerEvent = PointerEvent
```

**Comment by eps1lon** [comment] 2020-11-28 23:12
Closing since this issue is caused by the testing environment not any `@testing-library/*` package.

**Closed by eps1lon** 2020-11-28 23:12 UTC

**Comment by szhsin** [comment] 2020-11-29 01:38
@marcosvega91 @eps1lon thanks for your comments and the workaround code.
