### ISSUE TITLE
Jest's afterEach(cleanup) when rendering svg's causes Error: Uncaught [TypeError: this.node.getScreenCTM is not a function]

### ISSUE THREAD

**Issue by rodpatulski** [testing-library/react-testing-library#1116] opened 2022-08-26 23:07 UTC
- `@testing-library/react` version: 13.3.0
- Testing Framework and version: jest@26.6.0, react@18.2.0, jsdom@16.4.0

### Relevant code or config:

```js
// in app.test.js
import '@testing-library/react/dont-cleanup-after-each';
afterEach(cleanup);

it('renders the app without errors', done => {

  render(<App />);
  
});
```

app.js renders an svg chart. (Apexcharts)
### What you did:

Ran npm test

### What happened:

Error: Uncaught [TypeError: this.node.getScreenCTM is not a function]

### Problem description:

When I setup cleanup with jest either through its automatic feature or by turning it off and calling it manually in 'afterEach'. 
```js
afterEach(cleanup);
```
The code breaks. 

If I use:
```js
// in app.test.js
afterEach(() => {
  setTimeout(() => {
    cleanup(); 
  }, 1);
});
```

Things work fine.
### Suggested solution:

For some reason, cleanup seems to be called prematurely (before all the unmounting events?). 
The solution needs to play well with jest's afterEach mechanism and cleanup.

**Comment by MatanBobi** [comment] 2022-08-28 06:49
Thanks for opening this one @rodpatulski.
If I understand correctly, we're not `await`ing for the unmount, we're just calling [`root.unmount()`](https://github.com/testing-library/react-testing-library/blob/73ee9ba13cb4b337f06e2ed61099d6af9a4968da/src/pure.js#L81) so what you're experiencing seems reasonable. There's probably something happening on `unmount` of `Apexcharts`.
From a first look at the repo, it looks like it's using class components so I highly doubt they support React 18.

**Comment by rodpatulski** [comment] 2022-08-28 17:54
> I highly doubt they support React 18.

I forgot to mention that this was happening to me as early as react 16. (I recently updated to 18)

**Comment by eps1lon** [comment] 2022-08-31 06:59
Seems like something is not cleaning up properly during unmount. Without knowing the full source, we won't be able to know where the issue is coming from. Try to remove as much code as possible until it no longer reproduces and share that either via [codesandbox](https://react.new) or a cloneable repository.

**Comment by rodpatulski** [comment] 2022-09-01 00:54
Here's a repo that recreates the problem:
Run npm test to recreate. 
https://github.com/rodpatulski/bug-jest-cleanup

**Comment by eps1lon** [comment] 2022-09-04 13:57
> ```js
> afterEach
> ```

@rodpatulski In the README you write

> Uncomment afterEach(cleanup) line to see that the test passes without cleanup.

But I can't find that line. Are you sure you included all the relevant code?

**Comment by rodpatulski** [comment] 2022-09-20 02:34
Sorry, forgot to push a commit. The 'afterEach(cleanup) is in app.test.js ln 7.

**Comment by eps1lon** [comment] 2022-10-08 09:59
Since this relies on a 3rd party library (`react-apexcharts`) I would suggest filing an issue against their repository first. Or try to reduce the repro to code that's not using 3rd party code.

**Comment by eps1lon** [comment] 2022-12-06 20:33
Closing since no minimal reproduction was provided within 14 days.

**Closed by eps1lon** 2022-12-06 20:33 UTC
Labels: needs more information
