### ISSUE TITLE
@types/testing-library__react"' has no exported member 'waitFor'.  ts(2305)

### ISSUE THREAD

**Issue by ApolloTang** [testing-library/react-testing-library#613] opened 2020-03-17 07:33 UTC
- `@testing-library/react` version: 10.0.1
- `react` version:  16.13.0
- `node` version: v12.14.0
- `npm` (or `yarn`) version: 1.22.1

### Relevant code or config:

```js
node_modules/@types/testing-library__react"' has no exported member 'waitFor'.ts(2305)
```

### What happened:

waitFor is working great, but missing type

**Comment by eps1lon** [comment] 2020-03-17 09:51
Duplicate of #610.

**Closed by eps1lon** 2020-03-17 09:51 UTC
