### ISSUE TITLE
Support React 18 which uses ReactDOM `createRoot` instead of `render`

### ISSUE THREAD

**Issue by chrisbull** [testing-library/react-testing-library#933] opened 2021-06-13 19:18 UTC
### Describe the feature you'd like:

Getting error when using React 18 `react@alpha` or `react@experimental`

I'm using React18 to get the new Suspense feature. When doing so, I have to upgrade ReactDOM which now throws an error to use `createRoot` instead of `render`

### Suggested implementation:

Build in support for both `createRoot` and `render`

### Describe alternatives you've considered:

In the `testing-library@alpha` build it to work with `react-dom@alpha`

### Teachability, Documentation, Adoption, Migration Strategy:

See this for documentation: https://github.com/reactwg/react-18/discussions/5

**Comment by eps1lon** [comment] 2021-06-13 19:48
Thanks for the feedback.

> I'm using React18 to get the new Suspense feature. When doing so, I have to upgrade ReactDOM which now throws an error to use createRoot instead of render

It should log an error to the console not throw if I remember correctly.

Closing as a duplicate of https://github.com/testing-library/react-testing-library/issues/509. You can try https://github.com/testing-library/react-testing-library/pull/925 in the meantime.

**Closed by eps1lon** 2021-06-13 19:48 UTC
