### ISSUE TITLE
TypeError: (intermediate value) is not a function

### ISSUE THREAD

**Issue by AnubhutiRoX** [testing-library/react-testing-library#998] opened 2021-11-29 15:35 UTC
I am using react 17, redux 4, react-redux 7 and @testing-library/react 11. I am trying to write Junit for button click event, where I am calling a backend API and setting the returned result in redux. 

TypeError: (intermediate value) is not a function

      44 |     const onEditClickHandler = async (): Promise<void> => {
      45 |         console.log("******** EDIT ********", showModal);
    > 46 |         (await callAction(props.id))(dispatch);
         |         ^
      47 |         setShowModal(true);
      48 |     };
      49 |
callAction is the action creator - 

export const callAction = async (
    id:string
) => {
    return async (dispatch: any): Promise<IAction> => {
        try {
            const res = await axios.post(`/dummy`, {
               id
            });
            return dispatch({
                type: GET_DATA,
                payload: res.data
            });
        } catch (e) {
            return dispatch({
                type: ERROR,
                payload: (e)
            });
        }
    };
};

This code runs perfectly fine in the application. What is the issue with the test case

**Comment by eps1lon** [comment] 2021-11-29 15:37
It doesn't look like this bug report has enough info for one of us to reproduce it.

Please provide a CodeSandbox, a link to a repository on GitHub, or provide a minimal code example that reproduces the problem. 

Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by eps1lon** [comment] 2022-03-02 10:14
Closing since no reproduction was provided in 3 months.

**Closed by eps1lon** 2022-03-02 10:14 UTC
Labels: needs more information
