### ISSUE TITLE
React lazy load component not able to find the text in props

### ISSUE THREAD

**Issue by brendonco** [testing-library/react-testing-library#920] opened 2021-06-02 02:10 UTC
https://codesandbox.io/s/react-lazy-component-testing-forked-gyc2q?file=/src/LazyComponent.test.js

LazyComponent.js
```
import React from "react"

export default ({ title, count }) => (
  <div>
    <h1>`${title} (${count})`</h1>
    <p>
      This component is Lazy and will be imported after 1000ms, you should be
      able to see "Loading". Reload if you didn't
    </p>
  </div>
)

```

If I used variable to assert the text, the test will failed.  If I change the variable to the exact text assigned to the variable, it works. any reason why?

LazyComponent.test.js
```
import React, { lazy, Suspense } from "react"
import { render, screen } from "@testing-library/react"
// For codeSandbox
import "@testing-library/jest-dom/extend-expect"

const LazyComponent = lazy(() => import("./LazyComponent"))

test("renders lazy component", async () => {
  // Will render the lazy component
  const title = "I'm so lazy";
  const count = 1;
  render(
    <Suspense fallback={<p>Loading...</p>}>
      <LazyComponent title={title} count={count}/>
    </Suspense>
  )
  // Match text inside it
  const textToMatch = await screen.findByText(title)
  expect(textToMatch).toBeInTheDocument()
})
```

Here's a sample code to test.
https://codesandbox.io/s/react-lazy-component-testing-forked-gyc2q?file=/src/LazyComponent.js:0-265

**Comment by eps1lon** [comment] 2021-06-02 09:17
Thanks for the feedback.

This is intended behavior of `findByText`:

> This will search for all elements that have a text node with textContent matching the given TextMatch.

-- https://testing-library.com/docs/queries/bytext

What you probably want is a non-exact match like so:

```diff
-const textToMatch = await screen.findByText(title)
+const textToMatch = await screen.findByText(title, {exact:false})
```


Does this clear things up?

**Comment by eps1lon** [comment] 2022-04-13 14:45
Closing since no the issue author is unresponsive.

**Closed by eps1lon** 2022-04-13 14:45 UTC
Labels: question
