### ISSUE TITLE
TypeError: Failed to execute 'createTreeWalker' on 'Document': parameter 1 is not of type 'Node'.

### ISSUE THREAD

**Issue by maxi-groldan** [testing-library/react-testing-library#1165] opened 2023-01-06 14:18 UTC
Hi!
I am develop two test using Testing Library and jest. If run each one separately they work successfully. If I run both together (describe), the second one always failed with the following message **_"TypeError: Failed to execute 'createTreeWalker' on 'Document': parameter 1 is not of type 'Node'."_**. They do not have any dependency between them. I searched on Internet but I did not find anything that can help me. 
The error is thrown when I search a button with screen.getByTestId

Could you help me?

![image](https://user-images.githubusercontent.com/79223451/211030152-28139633-0586-48ae-a7b4-93600cbb0a78.png)

Config:
@testing-library/dom: 8.11.1
@testing-library/react: 12.1.2
@testing-library/user-event: 13.5.0

Node: 14.17.5

React: 17

Thanks in advance!

**Comment by eps1lon** [comment] 2023-01-07 14:16
It doesn't look like this bug report has enough info for one of us to reproduce it.

Please provide a CodeSandbox (https://react.new), or a link to a repository on GitHub.

Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by evargast** [comment] 2023-01-31 18:54
Hey @maxi-groldan ! Looking at the stack trace error, it seems like you might be using [@adobe/react-spectrum](https://www.npmjs.com/package/@adobe/react-spectrum).

Some components behind the scenes are using a component called [OpenTransition](https://github.com/adobe/react-spectrum/blob/main/packages/%40react-spectrum/overlays/src/OpenTransition.tsx#L41) which has a timeout of 350ms, this can make it tricky to test sometimes.

If this is the case I would suggest you create a test-utils helper function, such as the one below and call it after an interaction that would trigger this transition, such as a popover closing for example. This will give the transition time to close smoothly and prevent the treeWalker that is being used to track the focus from being in an undefined state.

```javascript
function timeout(ms = 400): Promise<void> {
	return act(async () => {
		await new Promise((resolve) => setTimeout(resolve, ms));
	});
}
``` 

If you encounter any issues while testing a particular component, I would also suggest you go to [our repository](https://github.com/adobe/react-spectrum) and check how the components are being tested! 😄

**Comment by eps1lon** [comment] 2023-02-16 17:20
Closing since no repro was provided

**Closed by eps1lon** 2023-02-16 17:20 UTC
Labels: needs more information
