### ISSUE TITLE
Can't getByRole with name and hidden: true

### ISSUE THREAD

**Issue by diegohaz** [testing-library/react-testing-library#1008] opened 2022-01-03 16:51 UTC
- `@testing-library/react` version: 12.1.2
- Testing Framework and version: `react-scripts` 5.0.0
- DOM Environment: jsdom in `react-scripts` 5.0.0

### What you did:

I'm trying to get a hidden element using `getByRole`, passing a `name` and setting `hidden` to `true`.

### What happened:

It looks like the element name is empty when the element is hidden even when passing `hidden: true` to the options. Not sure if it's intended, but that's not what I expect. The same happens with `aria-label`.

This is the error:

```
Unable to find an element with the role "dialog" and name "Title"

Here are the available roles:

  dialog:

  Name "":
  <div
    aria-labelledby="title"
    hidden=""
    role="dialog"
  />
```

### Reproduction:

https://codesandbox.io/s/react-testing-library-does-not-find-hidden-element-by-accessible-name-6ncd2

**Comment by MatanBobi** [comment] 2022-01-06 20:49
Hi @diegohaz, thanks for taking the time to open this one :)
I'm closing this as duplicate of https://github.com/testing-library/dom-testing-library/issues/846
You can track the progress in there.
Thanks again!

**Closed by MatanBobi** 2022-01-06 20:49 UTC
