### ISSUE TITLE
useEffect only triggered once from the very beginning

### ISSUE THREAD

**Issue by ningji** [testing-library/react-testing-library#1009] opened 2022-01-15 19:00 UTC
- `@testing-library/react` version: 11.2.7
- Testing Framework and version: jest console 26.6.3
- `@testing-library/jest-dom` 5.15.0

i have this piece of code works in manual test, when i load the react app in my local machine.

```
const MyModal = (props) => {
  const { modalTitle } = props;

  // myFetch calls into backend server and returns some json data 
  const {
    isLoading, isError, data,
  } = useQuery(['myQuery', { userId: auth.userId }], myFetch);

  console.error('----0----');
  console.error(JSON.stringify(data));
  console.error('----0----');

  useEffect(() => {
    console.error('----3----');
    console.error(JSON.stringify(data));
    console.error('----3----');
    // here post-process the (data) from myFetch
    setState(processedData);
  }, [data]);

  if (isShowing === false) return null;

  if (isLoading) {
    return <h1>{LOADING}</h1>;
  }

  if (isError || data?.isError) {
    return (
      <h1>
        {ERROR_MSG}
      </h1>
    );
  }

  .....

  return (
    <div>
      <h4>{modalTitle}</h4>
      <h5>some info based on the processed data</h5>
    </div>
  }
}

MyModal.defaultProps = {
  modalTitle: 'My title'
}
```
But in the unit test, i see useEffect only called once from very beginning. Basically i see several '----0----', initially the data is undefined, finally it's the mock data. But '----3----' only shows once while the data is undefined.

```
import React from 'react';
import { render, screen, waitFor } from '@testing-library/react';
import MyModal from '../MyModal';

beforeEach(() => {
  jest.spyOn(global, 'fetch').mockResolvedValue({
    ok: true,
    status: 200,
    json: jest.fn().mockResolvedValue(myMockJsonData),
  });

  useAuth.mockReturnValue({ userId: 12345 });
});

afterEach(() => {
  jest.restoreAllMocks();
  jest.useRealTimers();
});

  describe.only('Title', () => {
    it('heading is shown with title passed in as prop', async () => {
      render(translate(queryWrapper(<MyModal />)));
      const titleHeader = await screen.findByText('My title');
      expect(titleHeader).toBeInTheDocument();
    });
  });
```
You can ignore our QueryWrapper, the test basically renders our modal. So while in manual test it works, but not in this unit test ? How to fix UT pls ? Thx !

**Comment by ningji** [comment] 2022-01-17 19:30
i have a feeling, just waiting for the title might not be enough ? useEffect calls setState, state change might happen 1 cycle after the useQuery returns data ?

**Comment by MatanBobi** [comment] 2022-01-22 17:53
Hi @ningji, thanks for taking the time to open this one.
The component code you attached doesn't seem related to the test you wrote. Can you please share a reproducible example or fix the code you attached?
Basically in order to wait for all side effects to complete and to test the component the way it's used, you should wait for a loader or the component to actually appear. What do you mean waiting for the title might not be enough?

**Comment by ningji** [comment] 2022-01-24 00:56
Hi @MatanBobi, thanks for the reply, i'll take a look at my test again. If no one else had similar issue, then most likely it's my test.

**Comment by MatanBobi** [comment] 2022-02-22 19:26
@ningji Since you didn't post something here for about a month, I'm thinking that you may have resolved this one.
I'm closing it but please feel free to comment here with more details and I'll re-open it.

Thanks! :)

**Closed by MatanBobi** 2022-02-22 19:26 UTC
