### ISSUE TITLE
@testing-library/react  needs lock  @testing-library/dom version in currentPackage

### ISSUE THREAD

**Issue by mumiao** [testing-library/react-testing-library#942] opened 2021-07-16 04:34 UTC
- `@testing-library/react` version: 10.0.1
- Testing Framework and version:  React 16.9.51，Jest 26.1.0
  
- DOM Environment:  5.11.0
  

### What you did:
 Regenrate yarn.lock by excute yarn install scripts

### What happened:
   although @testing-library/react package lock version 10.0.1，but it depends on @testing-library/dom@^7.0.2  package that 
version is not locked，finally @testing-library/dom package  upgrade 8.1.0 that configured out node engine version >= 12

![image](https://user-images.githubusercontent.com/22880945/125891628-5f55ba87-d401-4ae6-bd18-d67ac21aa015.png)

Even if Node is upgraded locally and develop, the server environment is complicated and needs to be backward compatible，
this server environment unable to upgrade Node version  in a short time

### Suggested solution:

@testing-library/react package lock  @testing-library/dom verison 7.26.3 ，Especially update version of node engine  for @testing-library/dom package

**Comment by nickmccurdy** [comment] 2021-07-16 04:53
The Node team has officially dropped support for Node 10 as of April 30. We also dropped support for Node 10 recently, as it would take additional resources for us to continue to support it. Additionally, if any problems happen with Node rather than Testing Library, we can't fix them without requiring our users to upgrade Node, so even if we did support Node 10 it wouldn't necessarily work.

In the short term, you have the option of ignoring the Node version warning and seeing if it works, or downgrading to React Testing Library 11, which still had support for Node 10 (but if you do that, keep in mind that you're still using a version of Node that is not officially supported).

In the long term, I'd recommend following the [official Node release schedule](https://nodejs.org/en/about/releases/) to see what versions are supported (currently 12, 14, and 16) and when their support ends.

**Comment by mumiao** [comment] 2021-07-16 08:31
Currently  us depends on React Testing Library version maintain 10.0.1 that support for Node 10，but React Testing Library not locked Dom Testing Library version，so Dom Testing Library  upgraded the latest version that support for Node engines 12 version

**Comment by nickmccurdy** [comment] 2021-07-16 21:59
I'm not sure I understand what you mean. React Testing Library 10.0.1 depends on DOM Testing Library ^7.0.1 (meaning it can be version 7.0.1 or any 7.x after that version, as long as it's before 8.x). If you want to use React Testing Library 11, which has an engines requirement on Node >=12, read my last reply. If not, please explain in more detail what your goal is and what you think Testing Library could do to make it easier.

**Comment by mumiao** [comment] 2021-07-19 02:08
we expect  React Testing Library able to lock Dom Testing Library version (  it can be version 7.0.1 or any 7.x or 8.x), Dom Testing Library  be version 8.x that support  for Node 12

**Comment by eps1lon** [comment] 2021-07-19 07:46
> although @testing-library/react package lock version 10.0.1，but it depends on @testing-library/dom@^7.0.2 package that
version is not locked，finally @testing-library/dom package upgrade 8.1.0 that configured out node engine version >= 12

`^7.0.2` does not pull in `8.1.0` unless your package manager does not respect SemVer. All package managers I know of would not pull in `8.1.0` unless you explicitly tell your package manager to pull in the latest version in violation of SemVer.

Closing since no reproduction was provided.

**Closed by eps1lon** 2021-07-19 07:46 UTC
Labels: dependency

**Comment by nickmccurdy** [comment] 2021-07-19 08:12
Technically it's possible to have a `>=` version range in dependencies, but since recent versions of React Testing Library have only been tested with DOM Testing Library 8, it may not work well. If you'd like to try this you could create a fork, run the tests, and try a PR, but I'm not sure if it would be something we would support officially.

**Comment by mumiao** [comment] 2021-07-19 08:17
ok， thanks for your reply

**Comment by mumiao** [comment] 2021-07-19 11:51
```javascript
yarn add @testing-library/jest-dom@5.11.0 @testing-library/react@10.0.1 @testing-library/react-hooks@3.4.2
```
![Uploading image.png…]()

**Comment by mumiao** [comment] 2021-07-19 11:51
```javascript
yarn add @testing-library/jest-dom@5.11.0 @testing-library/react@10.0.1 @testing-library/react-hooks@3.4.2
```
![Uploading image.png…]()

**Comment by mumiao** [comment] 2021-07-19 11:58
![image](https://user-images.githubusercontent.com/22880945/126156513-575e1144-e059-4c5f-a6da-30c5ebb74198.png)

**Comment by nickmccurdy** [comment] 2021-07-20 03:08
That first screenshot seems to be part of your `yarn.lock`, but a dependency can be listed there multiple times if multiple versions are installed. The easiest way to check what versions are installed and why is `yarn why @testing-library/dom`.
