### ISSUE TITLE
14.0.0 gets stuck on await user-event with with vitest fake timer

### ISSUE THREAD

**Issue by neolivz** [testing-library/react-testing-library#1211] opened 2023-05-12 04:40 UTC
- `@testing-library/react` version: 14.0.0
- Testing Framework and version: vitest@0.31.0 
  
- DOM Environment: @testing-library/jest-dom@5.16.5 
  
- Other libraries: @testing-library/user-event@14.4.3

### Relevant code or config:

```js
    await user.click(screen.getByTestId("toggle-button"));
```

### What you did:
Update @testing-library/react version from 13.4.0 to 14.0.0

### What happened:
Test started failing

### Reproduction:
https://codesandbox.io/p/sandbox/relaxed-water-1bm3wr?welcome=true
Run pnpm test
The test fails as long as the @testing-library/react version is 14.0.0 and works fine with 13.4.0

**Comment by GiorgosPap** [comment] 2023-05-15 09:40
Same problem here

**Comment by BreakBB** [comment] 2023-05-25 15:25
I went the extra mile and went through the NPM 14.0.0-alpha versions and my test did not fail with `-alpha.14` and before, but with `-alpha.15` and above.

**Comment by BreakBB** [comment] 2023-05-25 15:29
This seems like a duplicate of #1197

**Closed** 2023-05-28 05:48 UTC
Labels: duplicate
