### ISSUE TITLE
Mocked axios get call response is getting set after rendering of component 

### ISSUE THREAD

**Issue by jayneesh** [testing-library/react-testing-library#1128] opened 2022-09-18 13:22 UTC
IN my react component i have a react data table. the data of which is fetched from axios get call. for testing of this component i have mocked the response which we get from axios get call . The mocked response is coming correctly but the table is coming empty . How to get the table rendered

**Comment by mstangret** [comment] 2022-09-18 16:12
I guess you should wait for the content either using `await.findBy` or `await waitFor`

**Comment by jayneesh** [comment] 2022-09-18 16:19
i am doing 
await waitFor(()=>screen.getByRole("table"));
I am getting a table but there are no rows

**Comment by mstangret** [comment] 2022-09-18 16:46
I can only guess without knowing the exact code. Maybe the table is rendered before the network response is received and this is why your test finishes before actual response data is presented?
If you mock the network response, can’t you wait for a particular piece of data? 

Nevertheless, it doesn’t sound like a RTL issue.

**Comment by MatanBobi** [comment] 2022-09-20 10:36
Hi @jayneesh..
As @mstangret, it looks like you need to await for something but we won't be able to help without a reproducible example.

In fact, these kind of questions are better asked in our [discord server](https://discord.gg/testing-library) or on stackoverflow.

I'm keeping this open for a couple of days hoping you'll attach a reproducible example, if you won't I'll close it and recommend again to ask this in the channels I attached above :)

**Comment by eps1lon** [comment] 2022-10-08 09:10
Closing since this is better handled in support channels (e.g. our [discord server](https://discord.gg/testing-library)) and no concrete repro was provided.

**Closed by eps1lon** 2022-10-08 09:10 UTC
Labels: question
