### ISSUE TITLE
Queries and RenderResult use incompatible types

### ISSUE THREAD

**Issue by pawbor** [testing-library/react-testing-library#841] opened 2020-12-02 08:31 UTC
- `@testing-library/react` version: 11.2.2
- Testing Framework and version: irrelevant
  
- DOM Environment: irrelevant
  

### Relevant code or config:

```js
it('example', () => {
  const { container } = render(<span>foo</span>); // container type is Element

  getByText(container as HTMLElement, 'foo'); // can't use container here without casting to HTMLElement
});
```

### What you did:

I tried to use container in custom query.

### What happened:

Types do not match without manual casting.

### Reproduction:

https://codesandbox.io/s/react-testing-library-demo-forked-bt601?file=/src/__tests__/hello.tsx

### Suggested solution:

Loosening type requirements for element provided to Queries

**Comment by MatanBobi** [comment] 2020-12-02 08:38
Hi @pawbor, thanks for taking the time to open this :)
This one looks like a duplicate of https://github.com/testing-library/dom-testing-library/issues/838.
@nickmccurdy is already working on a fix for this I believe.

**Comment by pawbor** [comment] 2020-12-02 08:43
Thank you! <3 I really appreciate all the work put in this library.

**Comment by nickmccurdy** [comment] 2020-12-03 11:42
You can follow https://github.com/testing-library/dom-testing-library/pull/834

**Closed by nickmccurdy** 2020-12-03 11:42 UTC
