### ISSUE TITLE
@testing-library/react run jest  TypeError: (0 , _dom.configure) is not a function

### ISSUE THREAD

**Issue by shashaMF** [testing-library/react-testing-library#1259] opened 2023-12-07 09:25 UTC
My problem is that I keep reporting this error while running Jest. If you know, please let me know. Thank you very much！
<img width="775" alt="image" src="https://github.com/testing-library/react-testing-library/assets/90231164/f770a1c7-15db-4582-92e6-ba15378793f4">
{
    "@testing-library/dom": "9.0.0",
    "@testing-library/jest-dom": "6.1.5",
    "@testing-library/react": "12.1.3",
    "@testing-library/user-event": "^12.1.10",
     "react": "^17.0.1",
}

**Comment by agentdylan** [comment] 2023-12-07 09:38
Similar report here, perhaps it can help?
https://github.com/testing-library/react-testing-library/issues/1055

Suggests it may be something to do with your jest `moduleNameMapper` config.

**Comment by MatanBobi** [comment] 2023-12-07 10:13
@shashaMF Can you please share a reproduction repo using [https://testing-library.com/new-rtl](https://testing-library.com/new-rtl)? At the moment we can't help because a screenshot doesn't help us a lot.
Also, you probably don't need to install `@testing-library/dom` because it comes bundled in with `@testing-library/react`.

**Comment by shashaMF** [comment] 2023-12-07 10:20
> @shashaMF您能否使用https://testing-library.com/new-rtl分享复制存储库？目前我们无能为力，因为屏幕截图对我们没有多大帮助。 另外，您可能不需要安装，`@testing-library/dom`因为它与`@testing-library/react`.

Sorry, we are an internal data system and do not have an external address.

I see that the @ testing library/react  code doesn't seem to recognize this way of writing：
<img width="519" alt="image" src="https://github.com/testing-library/react-testing-library/assets/90231164/f1e0247c-71d4-457e-b828-55ec345e4e2d">
I have never seen this function writing method before。
Can I uninstall @ testing library/dom。

**Comment by MatanBobi** [comment] 2023-12-07 10:22
Please share your jest config file and we'll try to help. It's written this way because the code is transpiled.

**Comment by shashaMF** [comment] 2023-12-07 10:25
> Please share your jest config file and we'll try to help. It's written this way because the code is transpiled.

![image](https://github.com/testing-library/react-testing-library/assets/90231164/4d93c27b-a91f-4f86-9c0a-f60f5f7a590a)
My jest config is stored in package.json。

Could you please help me take a look? Thank you very much！

**Comment by MatanBobi** [comment] 2023-12-08 14:33
@shashaMF these kind of questions are better asked in stackoverflow or in our [discord server](https://discord.gg/testing-library).
I'm closing this since there's no problem in RTL.
Thank you.

**Closed by MatanBobi** 2023-12-08 14:33 UTC

**Comment by shashaMF** [comment] 2023-12-11 01:59
> @shashaMF these kind of questions are better asked in stackoverflow or in our [discord server](https://discord.gg/testing-library). I'm closing this since there's no problem in RTL. Thank you.
My problem has been solved. It was caused by a configuration in my Jest configuration. Thanks!
