### ISSUE TITLE
screen.getAllByRole not working please update dependency

### ISSUE THREAD

**Issue by Mansi1** [testing-library/react-testing-library#877] opened 2021-02-10 14:33 UTC
Please update our dependency
`
import React from "react"
import { render, screen } from "@testing-library/react"
import { App } from "./App"

test("renders learn react link", () => {
  render(<App />)
  screen.getAllByRole("tab")
})
`

they fixed it in the testing library
https://github.com/testing-library/dom-testing-library/issues/553

**Comment by afontcu** [comment] 2021-02-10 15:04
Hi!

Not sure I follow 🤔 React Testing Library has a dependency on DOM Testing Library for [>7.28.1](https://github.com/testing-library/react-testing-library/blob/master/package.json#L47), so installing/updating your deps should get you the linked version.

**Comment by yonusbakhshi** [comment] 2021-02-11 11:50
@afontcu  all GetByRole, findByRole, queryByRole and their equivalent get/find/queryAllByRole don't work for buttons with role as tab!

**Comment by afontcu** [comment] 2021-02-11 11:52
Hi, you men the fix for the issue you linked is not working properly? If that's the case, it would be great if you could open up an issue in DOM Testing Lib repo with a reproduction link 🙌

**Comment by MatanBobi** [comment] 2021-03-18 08:35
Hi @Mansi1 @yonusbakhshi can we close this one or there is still something that needs to be addressed by us?

**Comment by MatanBobi** [comment] 2021-05-02 08:46
I'm closing this one as it looks like everything should work properly.
@Mansi1 @yonusbakhshi - If it's not, please feel free to comment here and I'll re-open it :)
Thanks everyone.

**Closed by MatanBobi** 2021-05-02 08:46 UTC
