### ISSUE TITLE
Found multiple elements by: [data-testid=

### ISSUE THREAD

**Issue by nagacoder** [testing-library/react-testing-library#536] opened 2019-11-19 04:17 UTC
can anyone explain how can the message Found multiple elements by, actually in the component there is only 1 data-testid,

```@testing-library/jest-dom": "4.0.0```
`@testing-library/react": "^8.0.9,`
`    "react": "^16.12.0",`
   ` "react-dom": "^16.12.0",`
---

![image](https://user-images.githubusercontent.com/32693625/69116007-4b800800-0abd-11ea-822e-d0419b504ba4.png)

**Comment by weyert** [comment] 2019-11-19 04:51
We would more information then this. Coul you post a reproducible sandbox example? Without code is a bit hard to see what could be going wrong here. Are you sure you are cleaning up after each test?

**Comment by kentcdodds** [comment] 2019-11-19 05:38
Hi @nagacoder,

Thanks @weyert! @weyert is correct, we'd need more information than this to help and a reproduction would really help. In addition, issues like this are best if posted to https://spectrum.chat/testing-library/help-react

Also, for @weyert:

> Are you sure you are cleaning up after each test?

That's automatic now, you shouldn't need to worry about it. :)

I'm going to go ahead and close this. Please take this to spectrum. Thanks @nagacoder!

**Closed by kentcdodds** 2019-11-19 05:38 UTC

**Comment by wallynm** [comment] 2020-01-15 17:28
Guys, i've just had this error and was easy to solve the problem.
I was changing branchs, and because of that my node_modules was different from what the package.json file.
To solve this i've just reinstalled the node_modules from scratch and worked fine!
The cleanup wasn't running correctly because some problem with version in my node_modules
Maybe this can help anyone with same problems!
