### ISSUE TITLE
[unexpected behavior] event propagation after fireEvent.keyDown not happening

### ISSUE THREAD

**Issue by sombreroEnPuntas** [testing-library/react-testing-library#487] opened 2019-09-23 16:10 UTC
Awesome library! :D

There's something unexpected regarding `fireEvent.keyDown` behavior and event propagation. Seems like the event is not propagated to parent components.

The use case was a bit more complex, so [here](https://codesandbox.io/s/react-testing-library-keydown-propagation-8q9ue) is a simplified version. It still seems to be missing the event.

Let's follow the template and describe a bit more:

### Relevant code or config:
- `react-testing-library` version: 9.1.4
- `react` version: 16.9.0
- `node` version: 12.10.0 (although this is not impacting, or is it?)
- `npm` (or `yarn`) version: 1.17.3

### What you did:
Inside the `Form` component, there's just a `form` and an `input`.
User is expected to write something on the input field, and then press enter.

Form submission via hitting enter should be allowed by default, and prevented when  a `preventEnterToSubmit` flag is set. This solution implements `e.preventDefault()` on the `keyDown` event.

### What happened:

On the code sandbox, there are test cases that (should) pass for both the positive and negative case of event propagation. Since it does not pass, it illustrates the unexpected propagation behavior :)

There's also a working app, that logs to the console which use case just happened: either submit after pressing Enter, or prevent submitting after pressing Enter. This seems to work as expected.

### Reproduction:
Project reproducing behavior:
https://codesandbox.io/s/react-testing-library-keydown-propagation-8q9ue

### Problem description:

Propagation is required for testing scenarios on which it is not possible (or hard) to pass an intermediate observer/spy/mock function, and the assertion is done on a parent component/element instead.

### Suggested solution:

Not sure if this is something the project wants to implement, open to feedback :D

**Comment by eps1lon** [comment] 2019-09-23 17:36
To clarify: The issue is that dispatching keydown event associated with the `Enter` key does not submit the form in the test.

This won't work without using the library either as far as I know. Form submission after pressing enter in an input is not defined in the spec but behavior that might be implemented by the user agent:

> If the user agent supports letting the user submit a form implicitly (for example, on some platforms hitting the "enter" key while a text field is focused implicitly submits the form)

-- https://www.w3.org/TR/html52/sec-forms.html#implicit-submission

How these events are constructed in the user agent I do not know. This is something that you should test with cypress to be sure you are only interested in the enter keydown.

It might make sense to implement this implicit form submission in https://github.com/testing-library/user-event#typeelement-text-options

**Comment by eps1lon** [comment] 2019-09-23 18:26
> > Not sure if this is something the project wants to implement, open to feedback :D
> 
> @eps1lon so is this feature on the scope of the library?

I think so. It's either a bug in `jsdom` or a feature for `user-event`. In any case I don't even know how you would construct this with just the DOM API. That would be my initial approach. But I'd like to hear from someone else who faced this issue and can share some insight.

**Comment by exah** [comment] 2019-09-24 10:35
I experience same problem when trying to test behaviour in custom `Select` component build on top of `downshift`:

```js
const handleSubmit = jest.fn()

const options = [
  { value: 1, label: 'First' },
  { value: 2, label: 'Second' },
  { value: 3, label: 'Third' },
]

const { getByTestId } = render(
  <form onSubmit={handleSubmit}>
    <Select options={options} />
  </form>,
)

const inputElement = getByTestId('input-select-inner-input')
expect(inputElement).toHaveValue('')

inputElement.focus()
fireEvent.keyDown(document.activeElement, { key: 'Enter', keyCode: 13 })

expect(inputElement).toHaveValue('First')

// Pressing enter in input inside also should submit form if default is not prevented, but currently we can't simulate it
expect(handleSubmit).not.toHaveBeenCalled()
```

**Comment by andypearson** [comment] 2019-12-20 11:17
Just bumped in to this issue myself, by writing almost exactly the same test as @exah :D

**Comment by kentcdodds** [comment] 2020-01-21 17:52
Hi folks 👋

I think this is out of scope for Testing Library. I think we can rely on the fact that if clicking the submit button or submitting on the form element submits the form properly, that the browser will behave properly when the user hits Enter on an input. I personally wouldn't bother writing a test for that behavior (because at that point you're basically testing the browser's features).

Thanks!

**Closed by kentcdodds** 2020-01-21 17:52 UTC
