### ISSUE TITLE
render component with one of its props as a component

### ISSUE THREAD

**Issue by brennanho** [testing-library/react-testing-library#612] opened 2020-03-13 19:03 UTC
- `@testing-library/react` version: 8.0.1
- `react` version: 16.8.x
- `node` version: 10.18.1
-  `yarn` version: 1.21.1 

Relevant code or config

```javascript
  it('should render Popover with body prop', () => {
    const bodyText = 'Test Body';
    const { getByTestId } = render(<Popover body={<div data-testid="test-body">{bodyText}</div>} />);
    const body = getByTestId('test-body');
   // Below doesn't work either
   // const body = document.querySelectorAll('div[data-testid="test-body"]');
    expect(body).toBeDefined();
    expect(body.innerHTML).toEqual(bodyText);
  });
```

What you did:

I am trying to test one of my components that takes a component as one of its props. It seems like this is the only instance where I cannot find the element in the dom i.e. a component/jsx is passed as a prop. 

What happened / Problem description:

Div element with data-testid="test-body" is not found in dom. Can verify nesting components is fine but issue only occurs when passing component via prop. 

Test:
![image](https://user-images.githubusercontent.com/21368908/76651266-61f51800-6521-11ea-8da5-72df9d82e365.png)
Component:
![image](https://user-images.githubusercontent.com/21368908/76652039-0035ad80-6523-11ea-9073-99f744eb62d2.png)
Console logging the body prop: 
![image](https://user-images.githubusercontent.com/21368908/76652094-1ba0b880-6523-11ea-9aeb-2a9a32cd5d70.png)
Subcomponent where body ends up (console log not captured?):
![image](https://user-images.githubusercontent.com/21368908/76652143-3410d300-6523-11ea-8111-85e7696821dd.png)

**Dom:**
![image](https://user-images.githubusercontent.com/21368908/76650994-ee530b00-6520-11ea-83c4-04367d233d34.png)

Suggested solution:

Not sure if perhaps this is bad coding practice or there is a way to test this but I need to test that a component prop is properly being passed through and rendered. Is the render method supposed to support this?

**Comment by kentcdodds** [comment] 2020-03-13 19:18
It looks like `StyledPopover` doesn't isn't rendering the `title` prop. Do you have to interact with the popover to get it to render its contents?

If you could make a reproduction following the steps in https://kcd.im/rtl-help and post that to [our spectrum](https://spectrum.chat/testing-library/help-react) then folks over there can help you.

Because we reserve issues for bugs and feature requests, I'm going to go ahead and close this. Thanks!

**Closed by kentcdodds** 2020-03-13 19:18 UTC
