### ISSUE TITLE
Make @types/react-dom a Peer dependency

### ISSUE THREAD

**Issue by daniel-nagy** [testing-library/react-testing-library#1318] opened 2024-04-29 17:21 UTC
### Describe the feature you'd like:

**@types/react-dom** is a dependency. The reason is that the types from **@testing-library/react** directly reference these types, as noted in this PR #1001.

However, this may cause multiple versions of these types to be installed in a user's project. For example, when updating to React 19 beta.

### Suggested implementation:

I think it would be better to make these types a peer dependency. If someone is using React, TypeScript, and React Testing Library, then they should install these types anyway.

In the event of a miss-match, they would get a warning from the package manager of an unmet peer-dependency, instead of the package manager silently installing multiple versions and resulting in a stampede of confusing type errors.

### Describe alternatives you've considered:

Use overrides to force the correct version of these types to be installed. This is not good DX.

### Teachability, Documentation, Adoption, Migration Strategy:

Users will need to install **@types/react-dom** themselves.

**Comment by MatanBobi** [comment] 2024-04-29 17:27
Thanks @daniel-nagy, this is already in the works: https://github.com/testing-library/react-testing-library/pull/1305.
I'm closing this as it's a duplicate of: https://github.com/testing-library/react-testing-library/issues/1184.

**Closed by MatanBobi** 2024-04-29 17:27 UTC

**Comment by daniel-nagy** [comment] 2024-04-29 17:29
Thanks @MatanBobi, I guess I should look at the open PRs next time 😅
