### ISSUE TITLE
Child element not extensible while under test

### ISSUE THREAD

**Issue by reidkersey** [testing-library/react-testing-library#823] opened 2020-11-10 20:16 UTC
- `@testing-library/react` version: 10.4.1
- Testing Framework and version: jest 25.5.4
  
- DOM Environment: "@testing-library/jest-dom": "^5.11.1",
  

### Relevant code or config:
Test Code
```js
    const { container, rerender } = render(
      <List value={['Test1', 'Test2']}>
        <ListItem value={'Test1'} children={'test1'} />
        <ListItem value={'Test2'} children={'test2'} />
        <ListItem value={'Test3'} children={'test3'} />
      </List>
    );
```

List
```typescript
    // standard functional component setup
    const {
      children,
      ...
    } = props;
   ...
   React.useEffect(() => {
      for (const val of value) {
        children
          .filter((child: { props: ListItemProps }) => child.props.value === val)
          .forEach((child: { props: ListItemProps }) => (child.props.checked = true));
      }
    }, [value]);
    //checked is a valid property of the child component
```

### What you did:
I ran test

### What happened:
    TypeError: Cannot add property checked, object is not extensible

      105 |         children
      106 |           .filter((child: { props: ListItemProps }) => child.props.value === val)
    > 107 |           .forEach((child: { props: ListItemProps }) => (child.props.checked = true));
          |                                                          ^
      108 |       }
      109 |     }, [value]);
      110 | 

### Problem description:
The above code works just fine while not under test, however, when used under test throws the error as seen above.

**Comment by nickmccurdy** [comment] 2020-11-10 20:46
Props in React are meant to be immutable. Mutating props can therefore cause unexpected behavior. I don't think this requires any changes to Testing Library, React doesn't support this so we don't have to either.

There may be a different way to implement this without the error though. Have you tried `cloneElement`? That will let you create new elements with different props, without dangerously mutating them.

**Comment by MatanBobi** [comment] 2021-03-18 08:39
Hi @reidkersey, looks like there's nothing left for us to do here so I'm closing this one. If you need any help from us, feel free to comment and I'll open it again :)

**Closed by MatanBobi** 2021-03-18 08:39 UTC
Labels: question

**Comment by jmtimko5** [comment] 2022-11-19 01:09
There are some libraries that require you to directly mutate props, and limitation means we cannot test them using RTL. I am surprised this would cause an error unless you are directly calling Object.preventExtensions. I know this is not best practice, but why prevent developers who might be in a sticky library situation

**Comment by jmtimko5** [comment] 2022-11-19 01:15
I am seeing this issue on object that are not passed in as props but are defined as variables in a function. The object is mutated in the function sure, but this has nothing to do with props, is this expected
```
let result;
	result = {
		label: chartMap.displayName,
		borderColor: colorMap[chartMap.datasetIndex % numColors],
		data: [],
		yAxisID: chartMap.columnKey,
		xAxisID,
	};
	// This is the line that causes the failure even though we are inside a function body and the variable above is a newly 
        // created object, not props
	result.columnKey = chartMap.columnKey;
```
